(function (root) {
  const grammarB1Worksheets = {
    "b1-futur-simple": [
      {
        id: "b1-futur-simple-s1",
        sheetNum: 1,
        title: "Sheet 1: Regular & Irregular Future Stems with Invariable Endings",
        subtitle: "20 Questions · Applying -ai, -as, -a, -ons, -ez, -ont to future radicals",
        exercises: [
          { q: "1. What are the six endings for the Futur Simple across all French verbs?", answer: "-ai, -as, -a, -ons, -ez, -ont" },
          { q: "2. What is the future stem of 'parler'?", answer: "parler- (the full infinitive: je parlerai)" },
          { q: "3. What is the future stem of 'finir'?", answer: "finir- (je finirai)" },
          { q: "4. What is the rule for verbs ending in -RE (e.g. prendre, attendre)?", answer: "Drop the final 'e' of the infinitive: prendr-, attendr- (je prendrai, j'attendrai)." },
          { q: "5. What is the irregular future stem of 'avoir'?", answer: "aur- (j'aurai, tu auras...)" },
          { q: "6. What is the irregular future stem of 'être'?", answer: "ser- (je serai, tu seras...)" },
          { q: "7. What is the irregular future stem of 'aller'?", answer: "ir- (j'irai, tu iras...)" },
          { q: "8. What is the irregular future stem of 'faire'?", answer: "fer- (je ferai, tu feras...)" },
          { q: "9. What is the irregular future stem of 'pouvoir'?", answer: "pourr- (double 'r': je pourrai)" },
          { q: "10. What is the irregular future stem of 'vouloir'?", answer: "voudr- (je voudrai)" },
          { q: "11. What is the irregular future stem of 'devoir'?", answer: "devr- (je devrai)" },
          { q: "12. What is the irregular future stem of 'savoir'?", answer: "saur- (je saurai)" },
          { q: "13. What is the irregular future stem of 'venir'?", answer: "viendr- (je viendrai)" },
          { q: "14. What is the irregular future stem of 'voir'?", answer: "verr- (double 'r': je verrai)" },
          { q: "15. What is the irregular future stem of 'envoyer'?", answer: "enverr- (j'enverrai)" },
          { q: "16. What is the irregular future stem of 'falloir' (impersonal)?", answer: "Il faudra" },
          { q: "17. Conjugate 'pleuvoir' in the Futur Simple.", answer: "Il pleuvra" },
          { q: "18. Conjugate 'recevoir' with 'Nous'.", answer: "Nous recevrons" },
          { q: "19. Conjugate 'tenir' with 'Ils'.", answer: "Ils tiendront" },
          { q: "20. Conjugate 'courir' with 'Je' (double 'r').", answer: "Je courrai" }
        ]
      },
      {
        id: "b1-futur-simple-s2",
        sheetNum: 2,
        title: "Sheet 2: Conjunctions of Time: Quand, Lorsque, Dès que",
        subtitle: "20 Questions · Mandatory French future tense in temporal clauses where English uses present",
        exercises: [
          { q: "1. Rule: When two clauses refer to the future linked by 'quand' or 'dès que', what tense does French require in BOTH clauses?", answer: "Futur Simple (unlike English, which uses the present tense after 'when/as soon as')." },
          { q: "2. Translate: 'When I arrive in Paris, I will call you.' (formal)", answer: "Quand j'arriverai à Paris, je vous appellerai." },
          { q: "3. Translate: 'As soon as he finishes the report, he will send it.'", answer: "Dès qu'il finira le rapport, il l'enverra." },
          { q: "4. Translate: 'When we have the results, we will inform the team.'", answer: "Lorsque nous aurons les résultats, nous informerons l'équipe." },
          { q: "5. Translate: 'As long as you are here, we will be happy.' (tant que)", answer: "Tant que tu seras ici, nous serons heureux." },
          { q: "6. Correct the error: 'Quand je suis prêt, je vais vous téléphoner.' (Future context)", answer: "Correction: 'Quand je SERAI prêt, je vous téléphonerai.'" },
          { q: "7. Correct the error: 'Dès qu'il a le temps, il le fera.'", answer: "Correction: 'Dès qu'il AURA le temps, il le fera.'" },
          { q: "8. Complete: Quand tu (partir) ___, ferme la porte à clé.", answer: "partiras (or pars in imperative context, but partira in pure future)" },
          { q: "9. Complete: Dès que nous (recevoir) ___ le virement, nous expédierons le colis.", answer: "recevrons" },
          { q: "10. Complete: Lorsque vous (être) ___ à l'hôtel, demandez la clé.", answer: "serez" },
          { q: "11. Translate: 'I will buy a house when I have enough money.'", answer: "J'achèterai une maison quand j'aurai assez d'argent." },
          { q: "12. Translate: 'We will celebrate as soon as the contract is signed.'", answer: "Nous fêterons cela dès que le contrat sera signé." },
          { q: "13. Translate: 'When they arrive, the conference will begin.'", answer: "Quand ils arriveront, la conférence commencera." },
          { q: "14. Translate: 'I will explain everything when I see you.' (informal)", answer: "Je t'expliquerai tout quand je te verrai." },
          { q: "15. Translate: 'As soon as the train stops, we will get off.'", answer: "Dès que le train s'arrêtera, nous descendrons." },
          { q: "16. Choose: Dès qu'elle (aura / a) le diplôme, elle postulera.", answer: "aura" },
          { q: "17. Choose: Quand ils (seront / sont) vieux, ils habiteront dans le Sud.", answer: "seront" },
          { q: "18. Translate: 'As long as the weather is nice, we will hike.'", answer: "Tant qu'il fera beau, nous ferons des randonnées." },
          { q: "19. Make negative: 'Quand je serai libre, je ne travaillerai pas.'", answer: "Quand je serai libre, je ne travaillerai pas." },
          { q: "20. Form a question: 'Quand viendrez-vous nous voir ?' (formal)", answer: "Quand viendrez-vous nous voir ?" }
        ]
      },
      {
        id: "b1-futur-simple-s3",
        sheetNum: 3,
        title: "Sheet 3: Professional Projections & Economic Forecasts",
        subtitle: "20 Questions · Formal pledges, market predictions and long-term commitments",
        exercises: [
          { q: "1. Translate: 'In 2030, our company will achieve carbon neutrality.'", answer: "En 2030, notre entreprise atteindra la neutralité carbone." },
          { q: "2. Translate: 'The inflation rate will decrease during the second quarter.'", answer: "Le taux d'inflation diminuera au cours du deuxième trimestre." },
          { q: "3. Translate: 'We will recruit fifty new software engineers.'", answer: "Nous recruterons cinquante nouveaux ingénieurs logiciels." },
          { q: "4. Translate: 'The new high-speed rail line will open next year.'", answer: "La nouvelle ligne à grande vitesse ouvrira l'année prochaine." },
          { q: "5. Translate: 'The mayor will inaugurate the cultural center on Saturday.'", answer: "Le maire inaugurera le centre culturel samedi." },
          { q: "6. Translate: 'Artificial intelligence will transform the labor market.'", answer: "L'intelligence artificielle transformera le marché du travail." },
          { q: "7. Translate: 'The government will announce new measures.'", answer: "Le gouvernement annoncera de nouvelles mesures." },
          { q: "8. Translate: 'Renewable energy will represent 40% of the energy mix.'", answer: "Les énergies renouvelables représenteront 40 % du mix énergétique." },
          { q: "9. Translate: 'We will guarantee full transparency to our investors.'", answer: "Nous garantirons une transparence totale à nos investisseurs." },
          { q: "10. Translate: 'Next century will see major technological breakthroughs.'", answer: "Le siècle prochain verra des percées technologiques majeures." },
          { q: "11. Conjugate: Les dépenses (augmenter) ___ de 3 %.", answer: "augmenteront" },
          { q: "12. Conjugate: Le conseil d'administration (prendre) ___ sa décision.", answer: "prendra" },
          { q: "13. Conjugate: Vous (recevoir) ___ une notification officielle.", answer: "recevrez" },
          { q: "14. Conjugate: Nous (devoir) ___ adapter notre stratégie.", answer: "devrons" },
          { q: "15. Conjugate: Ils ne (pouvoir) ___ pas participer.", answer: "pourront" },
          { q: "16. Translate: 'Will you support this initiative?' (formal)", answer: "Soutiendrez-vous cette initiative ?" },
          { q: "17. Translate: 'The project will generate thousands of jobs.'", answer: "Le projet générera des milliers d'emplois." },
          { q: "18. Translate: 'There will be fewer cars in city centers.'", answer: "Il y aura moins de voitures dans les centres-villes." },
          { q: "19. Translate: 'She will become the youngest partner of the firm.'", answer: "Elle deviendra la plus jeune associée du cabinet." },
          { q: "20. Translate: 'I will remain at your disposal for any further information.' (formal letter close)", answer: "Je resterai à votre disposition pour toute information complémentaire." }
        ]
      }
    ],

    "b1-conditional": [
      {
        id: "b1-conditional-s1",
        sheetNum: 1,
        title: "Sheet 1: Morphology (Future Stem + Imparfait Endings)",
        subtitle: "20 Questions · Structural formula for forming the present conditional",
        exercises: [
          { q: "1. What is the morphological formula for forming the Conditionnel Présent?", answer: "Future stem + Imparfait endings (-ais, -ais, -ait, -ions, -iez, -aient)." },
          { q: "2. Form the Conditionnel Présent: Je (parler)", answer: "Je parlerais" },
          { q: "3. Form the Conditionnel Présent: Tu (parler)", answer: "Tu parlerais" },
          { q: "4. Form the Conditionnel Présent: Il (parler)", answer: "Il parlerait" },
          { q: "5. Form the Conditionnel Présent: Nous (parler)", answer: "Nous parlerions" },
          { q: "6. Form the Conditionnel Présent: Vous (parler)", answer: "Vous parleriez" },
          { q: "7. Form the Conditionnel Présent: Ils (parler)", answer: "Ils parleraient" },
          { q: "8. Form the Conditionnel Présent: Je (vouloir)", answer: "Je voudrais (polite 'I would like')" },
          { q: "9. Form the Conditionnel Présent: Vous (pouvoir)", answer: "Vous pourriez ('Could you?')" },
          { q: "10. Form the Conditionnel Présent: Tu (aimer)", answer: "Tu aimerais" },
          { q: "11. Form the Conditionnel Présent: Il (falloir)", answer: "Il faudrait ('One should / It would be necessary')" },
          { q: "12. Form the Conditionnel Présent: Je (devoir)", answer: "Je devrais ('I ought to / I should')" },
          { q: "13. Form the Conditionnel Présent: Nous (avoir)", answer: "Nous aurions" },
          { q: "14. Form the Conditionnel Présent: Ils (être)", answer: "Ils seraient" },
          { q: "15. Form the Conditionnel Présent: Elle (faire)", answer: "Elle ferait" },
          { q: "16. Form the Conditionnel Présent: Nous (aller)", answer: "Nous irions" },
          { q: "17. Form the Conditionnel Présent: Vous (savoir)", answer: "Vous sauriez" },
          { q: "18. Form the Conditionnel Présent: Je (venir)", answer: "Je viendrais" },
          { q: "19. Form the Conditionnel Présent: Ils (prendre)", answer: "Ils prendraient" },
          { q: "20. Form the Conditionnel Présent: On (voir)", answer: "On verrait" }
        ]
      },
      {
        id: "b1-conditional-s2",
        sheetNum: 2,
        title: "Sheet 2: Values: Politeness, Advice & Unconfirmed Information",
        subtitle: "20 Questions · Softening requests, giving recommendations and journalistic attribution",
        exercises: [
          { q: "1. Translate politely: 'I would like a glass of water, please.'", answer: "Je voudrais un verre d'eau, s'il vous plaît." },
          { q: "2. Translate politely: 'Could you help me?' (formal)", answer: "Pourriez-vous m'aider ?" },
          { q: "3. Translate politely: 'Would you have a moment to talk?' (formal)", answer: "Auriez-vous un moment pour parler ?" },
          { q: "4. Give advice using 'devoir': 'You should sleep more.' (informal)", answer: "Tu devrais dormir plus." },
          { q: "5. Give advice using 'falloir': 'We ought to leave early.'", answer: "Il faudrait partir tôt." },
          { q: "6. Give advice: 'You should consult a physician.' (formal)", answer: "Vous devriez consulter un médecin." },
          { q: "7. Translate unconfirmed news (journalistic conditional): 'The president would be in Lyon today.'", answer: "Le président serait à Lyon aujourd'hui." },
          { q: "8. Translate unconfirmed news: 'The minister would be about to resign.'", answer: "Le ministre serait sur le point de démissionner." },
          { q: "9. Translate unconfirmed news: 'The strike would cause heavy delays.'", answer: "La grève causerait d'importants retards." },
          { q: "10. Express a wish: 'I would love to live in Quebec.'", answer: "J'aimerais vivre au Québec (or 'J'adorerais...')." },
          { q: "11. Express a wish: 'We would like to visit the museum.'", answer: "Nous aimerions visiter le musée." },
          { q: "12. Give friendly advice: 'If I were you, I would accept.' (À ta place...)", answer: "À ta place, j'accepterais." },
          { q: "13. Give advice: 'In your position, I wouldn't do that.' (À votre place...)", answer: "À votre place, je ne ferais pas cela." },
          { q: "14. Translate: 'Would it be possible to reschedule?'", answer: "Serait-il possible de reporter ?" },
          { q: "15. Translate: 'I would be delighted to meet you.' (formal)", answer: "Je serais ravi(e) de vous rencontrer." },
          { q: "16. Soften an opinion: 'It would seem that there is an error.'", answer: "Il semblerait qu'il y ait une erreur." },
          { q: "17. Translate: 'You ought to double-check the figures.' (formal)", answer: "Vous devriez revérifier les chiffres." },
          { q: "18. Translate: 'Who would want to work on Sunday?'", answer: "Qui voudrait travailler le dimanche ?" },
          { q: "19. Make negative: 'Je ne pourrais pas venir.'", answer: "Je ne pourrais pas venir." },
          { q: "20. Form an inverted polite question: 'Voudriez-vous prendre un café ?'", answer: "Voudriez-vous prendre un café ?" }
        ]
      },
      {
        id: "b1-conditional-s3",
        sheetNum: 3,
        title: "Sheet 3: Type 2 Hypotheses (Si + Imparfait → Conditionnel)",
        subtitle: "20 Questions · Constructing potential and counterfactual hypothetical structures",
        exercises: [
          { q: "1. What is the exact formula for Type 2 hypothetical clauses with 'Si'?", answer: "Si + Imparfait → Conditionnel Présent (e.g. Si j'avais le temps, je voyagerais)." },
          { q: "2. Does 'Si' ever directly take the conditional (e.g. 'Si j'aurais')?", answer: "NEVER! The classic French pedagogical rule is: 'Les 'si' n'aiment pas les 'rais'!' (never conditional after si)." },
          { q: "3. Complete: Si j' (avoir) ___ un million d'euros, j'achèterais une île.", answer: "avais (Imparfait after si)" },
          { q: "4. Complete: Si nous (gagner) ___ le match, nous serions champions.", answer: "gagnions" },
          { q: "5. Complete: Si tu (travailler) ___ plus, tu réussirais ton examen.", answer: "travaillais" },
          { q: "6. Complete: Si elle (être) ___ libre, elle viendrait avec nous.", answer: "était" },
          { q: "7. Complete: S'il (faire) ___ beau, nous ferions un pique-nique.", answer: "faisait" },
          { q: "8. Complete: Si vous (pouvoir) ___ choisir, où habiteriez-vous ?", answer: "pouviez" },
          { q: "9. Reverse clause order: 'J'accepterais l'offre si le salaire était meilleur.' Is this correct?", answer: "Yes, the order of clauses can be reversed without altering the tenses." },
          { q: "10. Translate: 'If I were rich, I would travel around the world.'", answer: "Si j'étais riche, je ferais le tour du monde." },
          { q: "11. Translate: 'What would you do if you were in my shoes?' (formal)", answer: "Que feriez-vous si vous étiez à ma place ?" },
          { q: "12. Translate: 'If we had a car, we could visit the villages.'", answer: "Si nous avions une voiture, nous pourrions visiter les villages." },
          { q: "13. Translate: 'If he knew the truth, he would be furious.'", answer: "S'il savait la vérité, il serait furieux." },
          { q: "14. Translate: 'If they lived in France, they would speak French fluently.'", answer: "S'ils habitaient en France, ils parleraient français couramment." },
          { q: "15. Correct the error: 'Si je saurais, je te le dirais.'", answer: "Correction: 'Si je SAVAIS, je te le dirais.' (Imparfait after si)" },
          { q: "16. Correct the error: 'Si j'aurais le temps, je viendrais.'", answer: "Correction: 'Si j'AVAIS le temps, je viendrais.'" },
          { q: "17. Complete: Si vous (vouloir) ___, nous pourrions commencer maintenant.", answer: "vouliez" },
          { q: "18. Translate: 'If the weather were bad, we would stay at the hotel.'", answer: "S'il faisait mauvais, nous resterions à l'hôtel." },
          { q: "19. Translate: 'If I didn't have to work, I would sleep all day.'", answer: "Si je ne devais pas travailler, je dormirais toute la journée." },
          { q: "20. Form a conditional wish with 'Si seulement' + Imparfait: 'If only I were on vacation!'", answer: "Si seulement j'étais en vacances !" }
        ]
      }
    ],

    "b1-plus-que-parfait-futur-anterieur": [
      {
        id: "b1-plus-que-parfait-futur-anterieur-s1",
        sheetNum: 1,
        title: "Sheet 1: Plus-que-parfait Morphology (Imparfait Aux + Participle)",
        subtitle: "20 Questions · Conjugating avaient/étaient + past participle for anteriority",
        exercises: [
          { q: "1. What is the structural formula for the Plus-que-parfait?", answer: "Auxiliary (Avoir or Être) in the IMPARFAIT + Past Participle." },
          { q: "2. Conjugate in Plus-que-parfait: Je (manger, avoir)", answer: "J'avais mangé" },
          { q: "3. Conjugate: Tu (finir, avoir)", answer: "Tu avais fini" },
          { q: "4. Conjugate: Il (comprendre, avoir)", answer: "Il avait compris" },
          { q: "5. Conjugate: Elle (partir, être with agreement)", answer: "Elle était partie" },
          { q: "6. Conjugate: Nous (visiter, avoir)", answer: "Nous avions visité" },
          { q: "7. Conjugate: Vous (prendre, avoir)", answer: "Vous aviez pris" },
          { q: "8. Conjugate: Ils (arriver, être with agreement)", answer: "Ils étaient arrivés" },
          { q: "9. Conjugate: Elles (naître, être with agreement)", answer: "Elles étaient nées" },
          { q: "10. Conjugate reflexive: Elle (se lever, être)", answer: "Elle s'était levée" },
          { q: "11. Conjugate reflexive: Nous (se dépêcher, être)", answer: "Nous nous étions dépêchés" },
          { q: "12. Conjugate: J' (avoir, avoir)", answer: "J'avais eu" },
          { q: "13. Conjugate: Il (être, avoir)", answer: "Il avait été" },
          { q: "14. Conjugate: Tu (faire, avoir)", answer: "Tu avais fait" },
          { q: "15. Conjugate: Nous (écrire, avoir)", answer: "Nous avions écrit" },
          { q: "16. Make negative: 'J'avais compris.'", answer: "Je n'avais pas compris." },
          { q: "17. Make negative: 'Elle était partie.'", answer: "Elle n'était pas partie." },
          { q: "18. Where do short adverbs go in Plus-que-parfait? (e.g. déjà)", answer: "Between the auxiliary and participle: 'J'avais déjà fini'." },
          { q: "19. Translate: 'I had already eaten when they arrived.'", answer: "J'avais déjà mangé quand ils sont arrivés." },
          { q: "20. What semantic relationship does the Plus-que-parfait establish with another past event?", answer: "Anteriority (the action occurred and was completed BEFORE another action in the past)." }
        ]
      },
      {
        id: "b1-plus-que-parfait-futur-anterieur-s2",
        sheetNum: 2,
        title: "Sheet 2: Narrative Timeline Alignment (PQP, PC, Imparfait)",
        subtitle: "20 Questions · Orchestrating three past tenses in coherent chronological prose",
        exercises: [
          { q: "1. Arrange from furthest past to most recent: Passé Composé, Plus-que-parfait, Présent.", answer: "1. Plus-que-parfait (past of the past) → 2. Passé Composé (recent completed past) → 3. Présent." },
          { q: "2. Complete: Quand je suis arrivé à la gare, le train (déjà partir) ___.", answer: "était déjà parti (PQP — departed prior to arrival)" },
          { q: "3. Complete: Elle m'a rendu le livre qu'elle (emprunter) ___ la semaine précédente.", answer: "avait emprunté" },
          { q: "4. Complete: Nous avons visité la maison que nos amis (acheter) ___ en juin.", answer: "avaient achetée (agreement with preceding COD que)" },
          { q: "5. Complete: Il ne trouvait plus ses clés car il les (oublier) ___ au bureau.", answer: "avait oubliées" },
          { q: "6. Complete: Sophie était fatiguée parce qu'elle (mal dormir) ___ la veille.", answer: "avait mal dormi" },
          { q: "7. Complete: Les policiers ont retrouvé la voiture que les voleurs (abandonner) ___.", answer: "avaient abandonnée" },
          { q: "8. Translate: 'I couldn't enter because I had lost my badge.'", answer: "Je ne pouvais pas entrer parce que j'avais perdu mon badge." },
          { q: "9. Translate: 'He told me that he had already signed the lease.'", answer: "Il m'a dit qu'il avait déjà signé le bail." },
          { q: "10. Translate: 'She showed me the photos she had taken in Rome.'", answer: "Elle m'a montré les photos qu'elle avait prises à Rome." },
          { q: "11. Translate: 'We realized that we had made a mistake.'", answer: "Nous avons réalisé (or compris) que nous avions fait une erreur." },
          { q: "12. Translate: 'The flight was cancelled, although we had booked months in advance.'", answer: "Le vol a été annulé, bien que nous eussions réservé (or alors que nous avions réservé des mois à l'avance)." },
          { q: "13. Correct the error: 'Quand j'ai arrivé, le film a déjà commencé.'", answer: "Correction: 'Quand je SUIS arrivé, le film AVAIT déjà commencé.'" },
          { q: "14. Correct the error: 'Elle m'a dit qu'elle a déjà vu ce film hier.'", answer: "Correction: 'Elle m'a dit qu'elle AVAIT déjà vu ce film...'" },
          { q: "15. Choose: Dès qu'il (avait fini / finissait), il est parti.", answer: "avait fini" },
          { q: "16. Translate: 'He didn't know the woman who had spoken to him.'", answer: "Il ne connaissait pas la femme qui lui avait parlé." },
          { q: "17. Translate: 'I remembered that I had promised to call.'", answer: "Je me suis souvenu que j'avais promis d'appeler." },
          { q: "18. Translate: 'The technician repaired the machine that had broken down.'", answer: "Le technicien a réparé la machine qui était tombée en panne." },
          { q: "19. Translate: 'We ate the cake she had baked.'", answer: "Nous avons mangé le gâteau qu'elle avait préparé." },
          { q: "20. Contrast: 'Il partait' vs. 'Il était parti'. What is the difference?", answer: "'Il partait' describes an ongoing action/departure in progress (Imparfait); 'Il était parti' confirms the departure was already completed (PQP)." }
        ]
      },
      {
        id: "b1-plus-que-parfait-futur-anterieur-s3",
        sheetNum: 3,
        title: "Sheet 3: Introduction to the Futur Antérieur (Future Anteriority)",
        subtitle: "20 Questions · Future auxiliary (aurai/serai) + participle for future actions preceding others",
        exercises: [
          { q: "1. What is the structural formula for the Futur Antérieur?", answer: "Auxiliary (Avoir or Être) in the FUTUR SIMPLE + Past Participle." },
          { q: "2. Form Futur Antérieur: Je (finir, avoir)", answer: "J'aurai fini" },
          { q: "3. Form Futur Antérieur: Tu (partir, être)", answer: "Tu seras parti(e)" },
          { q: "4. Form Futur Antérieur: Il (faire, avoir)", answer: "Il aura fait" },
          { q: "5. Form Futur Antérieur: Nous (arriver, être)", answer: "Nous serons arrivés" },
          { q: "6. Form Futur Antérieur: Vous (signer, avoir)", answer: "Vous aurez signé" },
          { q: "7. Form Futur Antérieur: Elles (rentrer, être)", answer: "Elles seront rentrées" },
          { q: "8. What semantic role does the Futur Antérieur play in a sentence with 'quand' or 'dès que'?", answer: "It expresses an action that will be completed BEFORE another future action begins." },
          { q: "9. Complete: Dès que j' (terminer) ___ ce projet, je prendrai des vacances.", answer: "aurai terminé" },
          { q: "10. Complete: Quand vous (lire) ___ le contrat, signez-le.", answer: "aurez lu" },
          { q: "11. Complete: Dès que nous (arriver) ___ à l'hôtel, nous vous appellerons.", answer: "serons arrivés" },
          { q: "12. Translate: 'As soon as I have received the transfer, I will ship the order.'", answer: "Dès que j'aurai reçu le virement, j'expédierai la commande." },
          { q: "13. Translate: 'When he has completed his training, he will be promoted.'", answer: "Quand il aura terminé sa formation, il sera promu." },
          { q: "14. Translate: 'By tomorrow noon, I will have finished.'", answer: "D'ici demain midi, j'aurai fini." },
          { q: "15. Translate: 'In five years, we will have repaid the loan.'", answer: "Dans cinq ans, nous aurons remboursé l'emprunt." },
          { q: "16. Make negative: 'Je n'aurai pas fini avant ce soir.'", answer: "Je n'aurai pas fini avant ce soir." },
          { q: "17. Where do pronouns go in Futur Antérieur? (e.g. 'le finir')", answer: "Before the future auxiliary: 'Je l'aurai fini'." },
          { q: "18. Translate: 'As soon as she has seen it, she will understand.'", answer: "Dès qu'elle l'aura vu, elle comprendra." },
          { q: "19. In hypothetical deductions, what does Futur Antérieur express? (e.g. 'Il se sera trompé')", answer: "A plausible supposition about a past event ('He must have made a mistake')." },
          { q: "20. Summarize the parallel between PQP and Futur Antérieur.", answer: "Both express anteriority (actions completed before a reference point): PQP looks back from a past reference point; Futur Antérieur looks back from a future reference point." }
        ]
      }
    ],

    "b1-direct-indirect-object-pronouns": [
      {
        id: "b1-direct-indirect-object-pronouns-s1",
        sheetNum: 1,
        title: "Sheet 1: Complex COD/COI Contrast & Verb Valencies",
        subtitle: "20 Questions · Determining transitive direct vs. indirect verb structures",
        exercises: [
          { q: "1. Does 'conseiller' take COD or COI for the person advised (e.g. conseiller quelqu'un or conseiller à quelqu'un)?", answer: "COI for the person: conseiller À quelqu'un de faire quelque chose (Je lui conseille)." },
          { q: "2. Does 'demander' take COD or COI for the person asked?", answer: "COI: demander À quelqu'un (Je lui demande)." },
          { q: "3. Does 'rappeler' take COD or COI for calling someone back on the phone?", answer: "COD: rappeler quelqu'un (Je le rappelle)." },
          { q: "4. Does 'téléphoner' take COD or COI?", answer: "COI: téléphoner À quelqu'un (Je lui téléphone)." },
          { q: "5. Does 'ressembler' take COD or COI?", answer: "COI: ressembler À quelqu'un (Il lui ressemble)." },
          { q: "6. Does 'inviter' take COD or COI?", answer: "COD: inviter quelqu'un (Je l'invite)." },
          { q: "7. Does 'obéir' take COD or COI in French?", answer: "COI: obéir À quelqu'un (Il leur obéit)." },
          { q: "8. Does 'plaire' take COD or COI?", answer: "COI: plaire À quelqu'un (Ce projet lui plaît)." },
          { q: "9. Does 'manquer' take COD or COI when expressing 'I miss you' (Tu me manques)?", answer: "COI: manquer À quelqu'un ('Tu me manques' = You are missing to me)." },
          { q: "10. Replace the object: 'J'ai conseillé à mon ami d'attendre.'", answer: "Je lui ai conseillé d'attendre." },
          { q: "11. Replace the object: 'Nous avons invité nos voisins.'", answer: "Nous les avons invités." },
          { q: "12. Replace the object: 'Le film a beaucoup plu aux spectateurs.'", answer: "Le film leur a beaucoup plu." },
          { q: "13. Replace the object: 'Il ressemble beaucoup à son père.'", answer: "Il lui ressemble beaucoup." },
          { q: "14. Replace the object: 'Tu as répondu à la cliente ?'", answer: "Tu lui as répondu ?" },
          { q: "15. Replace the object: 'J'attends le directeur depuis 20 minutes.'", answer: "Je l'attends depuis 20 minutes." },
          { q: "16. Correct the error: 'Je lui ai vu au supermarché.'", answer: "Correction: 'Je L'AI vu au supermarché.' (voir takes COD)" },
          { q: "17. Correct the error: 'Je l'ai téléphoné hier soir.'", answer: "Correction: 'Je LUI ai téléphoné hier soir.' (téléphoner takes COI)" },
          { q: "18. Translate: 'I will call him back in five minutes.'", answer: "Je le rappellerai dans cinq minutes." },
          { q: "19. Translate: 'We obeyed our managers.'", answer: "Nous leur avons obéi." },
          { q: "20. Translate: 'The proposal pleased the board.'", answer: "La proposition lui a plu (or leur a plu for the board members)." }
        ]
      },
      {
        id: "b1-direct-indirect-object-pronouns-s2",
        sheetNum: 2,
        title: "Sheet 2: Pronouns Y and EN in Complex Contexts",
        subtitle: "20 Questions · Mastering adverbial replacement of prepositional phrases (à vs. de)",
        exercises: [
          { q: "1. What preposition does 'Y' fundamentally replace (for non-persons)?", answer: "À (or other prepositions of place: en, dans, sur, sous) + thing or location." },
          { q: "2. What preposition does 'EN' fundamentally replace?", answer: "DE + thing/quantity, or partitive quantities." },
          { q: "3. If the complement is 'à + a person' (e.g. penser à son ami), do you use 'y' or a stress pronoun?", answer: "A STRESS PRONOUN: 'Je pense à lui' (never 'J'y pense' for people!)." },
          { q: "4. If the complement is 'de + a person' (e.g. parler de son père), do you use 'en' or a stress pronoun?", answer: "A STRESS PRONOUN: 'Je parle de lui' (never 'J'en parle' for human beings!)." },
          { q: "5. Replace with Y: 'Je vais à Paris demain.'", answer: "J'y vais demain." },
          { q: "6. Replace with Y: 'Il participe au projet.'", answer: "Il y participe." },
          { q: "7. Replace with Y: 'Elle pense à son avenir.'", answer: "Elle y pense." },
          { q: "8. Replace with Y: 'Nous habitons dans cet appartement depuis 2 ans.'", answer: "Nous y habitons depuis 2 ans." },
          { q: "9. Replace with EN: 'Tu as du café ? — Oui, j'ai (du café).'", answer: "Oui, j'en ai." },
          { q: "10. Replace with EN: 'Combien de livres as-tu ? — J'ai trois livres.'", answer: "J'en ai trois. (the numeral must be retained at the end)" },
          { q: "11. Replace with EN: 'Il parle de son travail.'", answer: "Il en parle." },
          { q: "12. Replace with EN: 'Elle a peur des araignées.'", answer: "Elle en a peur." },
          { q: "13. Replace with EN: 'Nous avons besoin de ce document.'", answer: "Nous en avons besoin." },
          { q: "14. Where does Y go in the near future: 'Je vais aller à la réunion.'", answer: "Before the infinitive: 'Je vais y aller'." },
          { q: "15. Where does EN go in Passé Composé: 'J'ai acheté des pommes.'", answer: "Before the auxiliary: 'J'en ai acheté'." },
          { q: "16. Does the past participle agree with 'en' in Passé Composé?", answer: "NO. Participles NEVER agree with 'en' (e.g. 'Des pommes ? J'en ai acheté', not achetées)." },
          { q: "17. Form affirmative imperative: 'Vas (à la gare) !' (Note euphonic -s added to va)", answer: "Vas-y ! (the -s is restored for pronunciation)" },
          { q: "18. Form affirmative imperative: 'Mange (des légumes) !' (with euphonic -s)", answer: "Manges-en !" },
          { q: "19. Make negative: 'N'y va pas !'", answer: "N'y va pas !" },
          { q: "20. Make negative: 'N'en prends pas !'", answer: "N'en prends pas !" }
        ]
      },
      {
        id: "b1-direct-indirect-object-pronouns-s3",
        sheetNum: 3,
        title: "Sheet 3: Double Pronoun Stacking Order with Y and EN",
        subtitle: "20 Questions · Complete pronoun hierarchy including Y and EN combinations",
        exercises: [
          { q: "1. In what position do Y and EN fall in the standard declarative pronoun order?", answer: "At the very end before the verb: [me/te/se/nous/vous] → [le/la/les] → [lui/leur] → [y] → [en]." },
          { q: "2. Can Y and EN appear together in standard French? What is the order?", answer: "Yes, 'Y' precedes 'EN': 'Il y en a' (There is/are some)." },
          { q: "3. Replace both complements: 'Il donne des pommes à moi.'", answer: "Il m'en donne." },
          { q: "4. Replace both: 'Je vous envoie les documents à votre bureau.'", answer: "Je vous les y envoie." },
          { q: "5. Replace both: 'Elle a prêté sa voiture à son frère.'", answer: "Elle la lui a prêtée." },
          { q: "6. Replace both: 'Nous parlons de ce projet à notre directeur.'", answer: "Nous lui en parlons." },
          { q: "7. Replace both: 'Tu as emmené les enfants au parc ?'", answer: "Tu les y as emmenés ?" },
          { q: "8. Replace both: 'Donnez-moi du pain !' (imperative)", answer: "Donnez-m'en !" },
          { q: "9. Replace both: 'Emmène-nous à la gare !' (imperative)", answer: "Emmène-nous-y !" },
          { q: "10. Make negative: 'Il m'en a parlé.'", answer: "Il ne m'en a pas parlé." },
          { q: "11. Make negative: 'Elle la lui a donnée.'", answer: "Elle ne la lui a pas donnée." },
          { q: "12. Make negative imperative: 'Donne-m'en !'", answer: "Ne m'en donne pas !" },
          { q: "13. Translate: 'Are there any left?' (using y and en)", answer: "Est-ce qu'il y en a encore ?" },
          { q: "14. Translate: 'There are no more left.'", answer: "Il n'y en a plus." },
          { q: "15. Translate: 'I will take you there tomorrow.' (formal)", answer: "Je vous y emmènerai demain." },
          { q: "16. Translate: 'Did you tell him about it?'", answer: "Tu lui en as parlé ?" },
          { q: "17. Correct the error: 'Donne-le-moi-y !'", answer: "French grammar avoids stacking three pronouns; rephrase to avoid clumsy clusters: 'Donne-le-moi là-bas !'" },
          { q: "18. Correct the error: 'Il en y a beaucoup.'", answer: "Correction: 'Il Y EN a beaucoup.' (y precedes en)" },
          { q: "19. Translate: 'We will bring some to them.'", answer: "Nous leur en apporterons." },
          { q: "20. Translate: 'She gave it to them yesterday.'", answer: "Elle le leur a donné hier." }
        ]
      }
    ],

    "b1-relative-pronouns-dont-ou": [
      {
        id: "b1-relative-pronouns-dont-ou-s1",
        sheetNum: 1,
        title: "Sheet 1: Relative Pronoun DONT: Verbs Governing 'DE'",
        subtitle: "20 Questions · Replacing prepositional de phrases (parler de, avoir besoin de, se souvenir de)",
        exercises: [
          { q: "1. What prepositional relationship does 'dont' replace in a relative clause?", answer: "Any phrase introduced by the preposition 'DE' (verbs with de, noun complements with de, adjective complements with de)." },
          { q: "2. Combine using DONT: 'C'est le livre. Je t'ai parlé de ce livre.'", answer: "C'est le livre dont je t'ai parlé." },
          { q: "3. Combine using DONT: 'Voici l'outil. J'ai besoin de cet outil.'", answer: "Voici l'outil dont j'ai besoin." },
          { q: "4. Combine using DONT: 'C'est un collègue. Je me souviens très bien de ce collègue.'", answer: "C'est un collègue dont je me souviens très bien." },
          { q: "5. Combine using DONT: 'C'est un projet. Nous sommes très fiers de ce projet.'", answer: "C'est un projet dont nous sommes très fiers." },
          { q: "6. Combine using DONT: 'Le film était captivant. Tout le monde parlait de ce film.'", answer: "Le film dont tout le monde parlait était captivant." },
          { q: "7. Fill in: L'appartement ___ j'ai envie est malheureusement trop cher.", answer: "dont (avoir envie DE)" },
          { q: "8. Fill in: Les compétences ___ vous disposez sont précieuses.", answer: "dont (disposer DE)" },
          { q: "9. Fill in: C'est une maladie ___ on guérit facilement aujourd'hui.", answer: "dont (guérir DE)" },
          { q: "10. Fill in: L'incident ___ il a été témoin s'est produit à 18h.", answer: "dont (être témoin DE)" },
          { q: "11. Translate: 'The document I need is on your desk.'", answer: "Le document dont j'ai besoin est sur votre bureau." },
          { q: "12. Translate: 'The person I was talking about just arrived.'", answer: "La personne dont je parlais vient d'arriver." },
          { q: "13. Translate: 'The results we are proud of were published yesterday.'", answer: "Les résultats dont nous sommes fiers ont été publiés hier." },
          { q: "14. What happens to the preposition 'de' when 'dont' is used?", answer: "The preposition 'de' is ABSORBED into 'dont' and MUST NOT be repeated (never 'dont je parle de'!)." },
          { q: "15. Correct the error: 'Le livre dont je t'ai parlé de lui.'", answer: "Correction: 'Le livre DONT je t'ai parlé.' (redundant de lui eliminated)" },
          { q: "16. Correct the error: 'Le document que j'ai besoin.'", answer: "Correction: 'Le document DONT j'ai besoin.' (avoir besoin DE requires dont)" },
          { q: "17. Fill in: C'est un sujet ___ nous avons discuté hier.", answer: "dont (discuter DE)" },
          { q: "18. Fill in: Le problème ___ il s'agit est complexe.", answer: "dont (s'agir DE)" },
          { q: "19. Translate: 'The candidate I am sure of.'", answer: "Le candidat dont je suis sûr(e)." },
          { q: "20. Translate: 'Everything you need is here.'", answer: "Tout ce dont vous avez besoin est ici." }
        ]
      },
      {
        id: "b1-relative-pronouns-dont-ou-s2",
        sheetNum: 2,
        title: "Sheet 2: DONT as Possessive Determiner ('Whose')",
        subtitle: "20 Questions · Expressing 'whose' and noun complements (le fils dont le père...)",
        exercises: [
          { q: "1. When 'dont' expresses possession ('whose'), what article must precede the possessed noun in French?", answer: "The DEFINITE article (le, la, les) MUST be retained: 'l'homme dont LA voiture' (unlike English, which drops 'the' after 'whose')." },
          { q: "2. Combine using DONT: 'J'ai rencontré une femme. Son fils étudie à Oxford.'", answer: "J'ai rencontré une femme dont le fils étudie à Oxford." },
          { q: "3. Combine using DONT: 'C'est un écrivain. Ses romans ont été traduits en 30 langues.'", answer: "C'est un écrivain dont les romans ont été traduits en 30 langues." },
          { q: "4. Combine using DONT: 'Nous visitons une entreprise. Le chiffre d'affaires de cette entreprise a doublé.'", answer: "Nous visitons une entreprise dont le chiffre d'affaires a doublé." },
          { q: "5. Combine using DONT: 'Voici un village. L'histoire de ce village remonte au Moyen Âge.'", answer: "Voici un village dont l'histoire remonte au Moyen Âge." },
          { q: "6. Fill in: C'est une collègue ___ les idées sont toujours innovantes.", answer: "dont" },
          { q: "7. Fill in: Un problème ___ la solution n'est pas évidente.", answer: "dont" },
          { q: "8. Translate: 'The client whose contract we renewed.'", answer: "Le client dont nous avons renouvelé le contrat." },
          { q: "9. Translate: 'The hotel whose rooms overlook the sea.'", answer: "L'hôtel dont les chambres donnent sur la mer." },
          { q: "10. Translate: 'A painter whose style is recognized worldwide.'", answer: "Un peintre dont le style est reconnu dans le monde entier." },
          { q: "11. What is the standard word order with 'dont' when the possessed noun is the direct object?", answer: "Subject + Verb + Direct Object: 'L'homme dont j'admire le courage' (NOT 'dont le courage j'admire')." },
          { q: "12. Correct the error: 'L'écrivain dont son livre a gagné le prix.'", answer: "Correction: 'L'écrivain dont LE livre a gagné le prix.' (son is forbidden with dont)" },
          { q: "13. Correct the error: 'La fille dont les yeux sont bleus.' Is this correct?", answer: "Yes, this is completely correct in French." },
          { q: "14. Correct the error: 'L'homme dont la femme je connais.'", answer: "Correction: 'L'homme dont je connais la femme.' (standard S-V-O order)" },
          { q: "15. Translate: 'The company whose employees are on strike.'", answer: "L'entreprise dont les employés sont en grève." },
          { q: "16. Translate: 'The artist whose works we exhibit.'", answer: "L'artiste dont nous exposons les œuvres." },
          { q: "17. Complete: C'est un dossier ___ les conclusions sont alarmantes.", answer: "dont" },
          { q: "18. Complete: Une ville ___ les rues sont très animées la nuit.", answer: "dont" },
          { q: "19. Translate: 'The student whose thesis won the award.'", answer: "L'étudiant dont la thèse a remporté le prix." },
          { q: "20. Translate: 'The director whose vision transformed the team.'", answer: "Le directeur dont la vision a transformé l'équipe." }
        ]
      },
      {
        id: "b1-relative-pronouns-dont-ou-s3",
        sheetNum: 3,
        title: "Sheet 3: Relative Pronoun OÙ for Place and Time",
        subtitle: "20 Questions · Distinguishing location 'où' and temporal 'où' ('when') from qui/que/dont",
        exercises: [
          { q: "1. What two distinct notions does the relative pronoun 'où' express in French?", answer: "Place (where) AND Time (when / on which)." },
          { q: "2. How do you say 'The day when I arrived' in French (Note: does it use 'quand' or 'où' as relative pronoun)?", answer: "Le jour OÙ je suis arrivé (never 'le jour quand'!)." },
          { q: "3. Combine using OÙ: 'C'est la ville. Je suis né dans cette ville.'", answer: "C'est la ville où je suis né." },
          { q: "4. Combine using OÙ: 'C'est l'année. Nous nous sommes mariés cette année-là.'", answer: "C'est l'année où nous nous sommes mariés." },
          { q: "5. Combine using OÙ: 'Voici le bureau. Je travaille dans ce bureau.'", answer: "Voici le bureau où je travaille." },
          { q: "6. Combine using OÙ: 'Au moment. Le téléphone a sonné à ce moment-là.'", answer: "Au moment où le téléphone a sonné." },
          { q: "7. Fill in with qui, que, dont, or où: La maison ___ j'ai achetée.", answer: "que (COD)" },
          { q: "8. Fill in with qui, que, dont, or où: La maison ___ se trouve au coin de la rue.", answer: "qui (subject)" },
          { q: "9. Fill in with qui, que, dont, or où: La maison ___ je t'ai parlé.", answer: "dont (parler de)" },
          { q: "10. Fill in with qui, que, dont, or où: La maison ___ nous habitons.", answer: "où (place / location)" },
          { q: "11. Fill in: L'époque ___ mes grands-parents vivaient à la campagne.", answer: "où (temporal antecedent 'l'époque')" },
          { q: "12. Fill in: Le restaurant ___ nous déjeunons le midi.", answer: "où" },
          { q: "13. Fill in: Le restaurant ___ nous préférons pour les dîners d'affaires.", answer: "que (préférer takes direct object, not place)" },
          { q: "14. Translate: 'The country where I grew up.'", answer: "Le pays où j'ai grandi." },
          { q: "15. Translate: 'The day when we signed the contract.'", answer: "Le jour où nous avons signé le contrat." },
          { q: "16. What is the compound relative 'd'où' used for?", answer: "Origin / provenance: 'from where' (e.g. 'La ville d'où je viens' = The city I come from)." },
          { q: "17. Translate: 'The city from which he comes.'", answer: "La ville d'où il vient." },
          { q: "18. Correct the error: 'Le moment quand il a parlé.'", answer: "Correction: 'Le moment OÙ il a parlé.' (quand is not a relative pronoun in French)" },
          { q: "19. Correct the error: 'L'hôtel où nous avons visité.'", answer: "Correction: 'L'hôtel que nous avons visité.' (visiter takes direct object COD, not location où)" },
          { q: "20. Fill in: C'est l'endroit exact ___ l'accident a eu lieu.", answer: "où" }
        ]
      }
    ]
  };

  root.GRAMMAR_B1_WORKSHEETS = grammarB1Worksheets;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = grammarB1Worksheets;
  }
})(typeof window !== "undefined" ? window : globalThis);
