(function (root) {
  const grammarA1ExtWorksheets = {
    "a1-pronouns-intro": [
      {
        id: "a1-pronouns-intro-s1",
        sheetNum: 1,
        title: "Sheet 1: Subject Pronouns & Basic Concord",
        subtitle: "20 Questions · Mastering je, tu, il, elle, on, nous, vous, ils, elles",
        exercises: [
          { q: "1. Which pronoun is used for informal 'you' (singular)?", answer: "Tu" },
          { q: "2. Which pronoun is used for formal 'you' (singular or plural)?", answer: "Vous" },
          { q: "3. What versatile third-person pronoun frequently replaces 'nous' in spoken French?", answer: "On (conjugates like il/elle in 3rd person singular)" },
          { q: "4. If a group has 99 women and 1 man, which plural pronoun is grammatically required?", answer: "Ils (the grammatical masculine rules the group in standard French)" },
          { q: "5. When referring to a group of only women, which plural pronoun is used?", answer: "Elles" },
          { q: "6. Replace the noun with a pronoun: 'Pierre habite à Paris.'", answer: "Il habite à Paris." },
          { q: "7. Replace the noun: 'Marie et Sophie travaillent ensemble.'", answer: "Elles travaillent ensemble." },
          { q: "8. Replace the noun: 'Thomas et moi préparons le rapport.'", answer: "Nous préparons le rapport (or 'On prépare...')." },
          { q: "9. Replace the noun: 'Julie et toi réservez une table.'", answer: "Vous réservez une table." },
          { q: "10. Replace the noun: 'La table est réservée.'", answer: "Elle est réservée. (table is feminine)" },
          { q: "11. Replace the noun: 'Le document est prêt.'", answer: "Il est prêt. (document is masculine)" },
          { q: "12. Replace the noun: 'Les valises sont prêtes.'", answer: "Elles sont prêtes." },
          { q: "13. Replace the noun: 'Les passeports sont dans le sac.'", answer: "Ils sont dans le sac." },
          { q: "14. Does 'Je' elide to 'J'' before a vowel?", answer: "Yes (e.g. J'habite, J'aime, J'écoute)." },
          { q: "15. Does 'Tu' elide to 'T'' in formal written French?", answer: "No. While common in informal spoken texting ('t'es là ?'), it is forbidden in standard written French." },
          { q: "16. Fill in the correct pronoun: ___ parlons français au travail.", answer: "Nous (or 'On' if the verb were 'parle')" },
          { q: "17. Fill in the correct pronoun: ___ ont vingt ans.", answer: "Ils (or Elles)" },
          { q: "18. Fill in the correct pronoun: ___ avez une question ?", answer: "Vous" },
          { q: "19. Fill in the correct pronoun: ___ es prêt pour la réunion ?", answer: "Tu" },
          { q: "20. Fill in the correct pronoun: Ce soir, ___ va au cinéma (informal 'we').", answer: "on" }
        ]
      },
      {
        id: "a1-pronouns-intro-s2",
        sheetNum: 2,
        title: "Sheet 2: Emphatic Stress Pronouns (Moi, Toi, Lui, Elle...)",
        subtitle: "20 Questions · Tonique pronouns for emphasis, after prepositions, and standing alone",
        exercises: [
          { q: "1. What is the stress pronoun corresponding to 'Je'?", answer: "Moi" },
          { q: "2. What is the stress pronoun corresponding to 'Tu'?", answer: "Toi" },
          { q: "3. What is the stress pronoun corresponding to 'Il'?", answer: "Lui" },
          { q: "4. What is the stress pronoun corresponding to 'Elle'?", answer: "Elle" },
          { q: "5. What is the stress pronoun corresponding to 'Nous'?", answer: "Nous" },
          { q: "6. What is the stress pronoun corresponding to 'Vous'?", answer: "Vous" },
          { q: "7. What is the stress pronoun corresponding to 'Ils'?", answer: "Eux [uh]" },
          { q: "8. What is the stress pronoun corresponding to 'Elles'?", answer: "Elles" },
          { q: "9. How do you say 'Me neither' in French?", answer: "Moi non plus" },
          { q: "10. How do you say 'Me too' in French?", answer: "Moi aussi" },
          { q: "11. Fill in the stress pronoun: Et ___, comment vous appelez-vous ? (formal)", answer: "vous (Et vous, ...)" },
          { q: "12. Fill in: Et ___, comment tu t'appelles ? (informal)", answer: "toi (Et toi, ...)" },
          { q: "13. Fill in: Je vais au restaurant avec ___ (with him).", answer: "lui (avec lui)" },
          { q: "14. Fill in: Ce cadeau est pour ___ (for them, m. pl.).", answer: "eux (pour eux)" },
          { q: "15. Fill in: Elle habite chez ___ (at her place).", answer: "elle (chez elle)" },
          { q: "16. Fill in: Viens chez ___ ce soir ! (at my place)", answer: "moi (chez moi)" },
          { q: "17. Provide emphatic duplication: ___, j'adore le café !", answer: "Moi (Moi, j'adore le café !)" },
          { q: "18. Provide emphatic duplication: ___, il déteste le thé !", answer: "Lui (Lui, il déteste le thé !)" },
          { q: "19. Answer the question standing alone: 'Qui veut un croissant ?' (Me!)", answer: "Moi ! (never 'Je !')" },
          { q: "20. Fill in: Paul et ___ (him) sont ingénieurs.", answer: "lui (Paul et lui sont ingénieurs)" }
        ]
      },
      {
        id: "a1-pronouns-intro-s3",
        sheetNum: 3,
        title: "Sheet 3: Contrastive Usage, Prepositions & Dual Subjects",
        subtitle: "20 Questions · Complex subjects, contrastive dialogue turns and prepositional complementation",
        exercises: [
          { q: "1. Translate: 'I like wine, but he prefers beer.' (Use stress pronouns for contrast)", answer: "Moi, j'aime le vin, mais lui, il préfère la bière." },
          { q: "2. Translate: 'She is traveling without him.'", answer: "Elle voyage sans lui." },
          { q: "3. Translate: 'We work for them (m.).'", answer: "Nous travaillons pour eux." },
          { q: "4. Translate: 'Come with us!'", answer: "Viens avec nous ! (or 'Venez avec nous !')" },
          { q: "5. Translate: 'Who is speaking? — It's me.'", answer: "Qui parle ? — C'est moi." },
          { q: "6. Translate: 'It's him.'", answer: "C'est lui." },
          { q: "7. Translate: 'It's them (m. pl.).'", answer: "Ce sont eux (or 'C'est eux' in spoken French)." },
          { q: "8. Translate: 'Are you staying at your parents' place?'", answer: "Tu restes chez eux ?" },
          { q: "9. Correct the error: 'Sans je, la réunion est annulée.'", answer: "Correction: 'Sans moi, la réunion est annulée.' (prepositions require stress pronouns)" },
          { q: "10. Correct the error: 'C'est il qui a le dossier.'", answer: "Correction: 'C'est lui qui a le dossier.'" },
          { q: "11. Fill in: Marie et ___ (me) partons à 14h.", answer: "moi (Marie et moi partons...)" },
          { q: "12. Fill in: Ni ___ (you, inf.) ni ___ (me) ne savons.", answer: "toi ... moi (Ni toi ni moi...)" },
          { q: "13. Fill in: Je pense souvent à ___ (her).", answer: "elle (Je pense à elle)" },
          { q: "14. Fill in: Ils ont besoin de ___ (us).", answer: "nous (Ils ont besoin de nous)" },
          { q: "15. Translate: 'She does it herself.'", answer: "Elle le fait elle-même." },
          { q: "16. Translate: 'I will do it myself.'", answer: "Je vais le faire moi-même." },
          { q: "17. What pronoun replaces 'on' when stressed or after a preposition?", answer: "'Soi' in general statements (e.g. 'Chacun pour soi') or 'nous' when referring to 'we'." },
          { q: "18. Translate: 'You and he are invited.' (formal)", answer: "Vous et lui êtes invités." },
          { q: "19. Translate: 'He arrived after me.'", answer: "Il est arrivé après moi." },
          { q: "20. Translate: 'Everyone is at home.' (at his/her own place)", answer: "Tout le monde est chez soi." }
        ]
      }
    ],

    "a1-futur-proche": [
      {
        id: "a1-futur-proche-s1",
        sheetNum: 1,
        title: "Sheet 1: Aller in the Present + Infinitive Formation",
        subtitle: "20 Questions · Mastering the immediate future construction (aller + infinitif)",
        exercises: [
          { q: "1. What auxiliary verb is conjugated to form the Futur Proche?", answer: "ALLER (in the present tense)" },
          { q: "2. Form the Futur Proche: Je (manger)", answer: "Je vais manger" },
          { q: "3. Form the Futur Proche: Tu (partir)", answer: "Tu vas partir" },
          { q: "4. Form the Futur Proche: Il (acheter)", answer: "Il va acheter" },
          { q: "5. Form the Futur Proche: Elle (travailler)", answer: "Elle va travailler" },
          { q: "6. Form the Futur Proche: On (visiter)", answer: "On va visiter" },
          { q: "7. Form the Futur Proche: Nous (prendre)", answer: "Nous allons prendre" },
          { q: "8. Form the Futur Proche: Vous (signer)", answer: "Vous allez signer" },
          { q: "9. Form the Futur Proche: Ils (arriver)", answer: "Ils vont arriver" },
          { q: "10. Form the Futur Proche: Elles (finir)", answer: "Elles vont finir" },
          { q: "11. Form the Futur Proche of 'aller' itself: Je (aller) à Paris.", answer: "Je vais aller à Paris." },
          { q: "12. Form the Futur Proche of 'être': Nous (être) en retard.", answer: "Nous allons être en retard." },
          { q: "13. Form the Futur Proche of 'avoir': Tu (avoir) du travail.", answer: "Tu vas avoir du travail." },
          { q: "14. Form the Futur Proche of 'faire': Il (faire) beau demain.", answer: "Il va faire beau demain." },
          { q: "15. Form the Futur Proche: Vous (commander) un dessert ?", answer: "Vous allez commander" },
          { q: "16. Form the Futur Proche: Je (téléphoner) au directeur.", answer: "Je vais téléphoner" },
          { q: "17. Form the Futur Proche: Ils (vendre) leur appartement.", answer: "Ils vont vendre" },
          { q: "18. Form the Futur Proche: Nous (réserver) les billets.", answer: "Nous allons réserver" },
          { q: "19. What time horizon does the Futur Proche typically convey?", answer: "Immediate future or a future action that is planned, certain, or visibly unfolding." },
          { q: "20. Form the Futur Proche: Tu (choisir) quelle option ?", answer: "Tu vas choisir" }
        ]
      },
      {
        id: "a1-futur-proche-s2",
        sheetNum: 2,
        title: "Sheet 2: Negative and Interrogative Near Future",
        subtitle: "20 Questions · Word order rules for ne... pas and questions in the near future",
        exercises: [
          { q: "1. Where do 'ne' and 'pas' go in the Futur Proche?", answer: "Around the conjugated verb ALLER (e.g. Je ne vais pas manger)." },
          { q: "2. Make negative: 'Je vais participer.'", answer: "Je ne vais pas participer." },
          { q: "3. Make negative: 'Tu vas accepter l'offre.'", answer: "Tu ne vas pas accepter l'offre." },
          { q: "4. Make negative: 'Il va pleuvoir.'", answer: "Il ne va pas pleuvoir." },
          { q: "5. Make negative: 'Nous allons signer aujourd'hui.'", answer: "Nous n'allons pas signer aujourd'hui. (n' before allons)" },
          { q: "6. Make negative: 'Vous allez attendre longtemps.'", answer: "Vous n'allez pas attendre longtemps." },
          { q: "7. Make negative: 'Ils vont partir en vacances.'", answer: "Ils ne vont pas partir en vacances." },
          { q: "8. Form a question with 'est-ce que': You are going to travel (formal).", answer: "Est-ce que vous allez voyager ?" },
          { q: "9. Form an inverted question: 'Vous allez partir.'", answer: "Allez-vous partir ?" },
          { q: "10. Form an inverted question: 'Il va téléphoner.' (Note euphonic -t-)", answer: "Va-t-il téléphoner ?" },
          { q: "11. Where does an object pronoun go in the Futur Proche (e.g. 'le voir')?", answer: "Directly in front of the INFINITIVE (e.g. 'Je vais le voir', not 'Je le vais voir')." },
          { q: "12. Translate: 'I am going to see him.'", answer: "Je vais le voir." },
          { q: "13. Translate: 'I am not going to see him.'", answer: "Je ne vais pas le voir." },
          { q: "14. Translate: 'Are you going to call her?' (formal)", answer: "Allez-vous l'appeler ? (or 'Vous allez l'appeler ?')" },
          { q: "15. Translate: 'We are going to invite them.'", answer: "Nous allons les inviter." },
          { q: "16. Correct the error: 'Je ne manger vais pas.'", answer: "Correction: 'Je ne vais pas manger.'" },
          { q: "17. Correct the error: 'Je le vais faire demain.'", answer: "Correction: 'Je vais le faire demain.'" },
          { q: "18. Make negative: 'Elle va acheter cette robe.'", answer: "Elle ne va pas acheter cette robe." },
          { q: "19. Make negative: 'On va être prêts à l'heure.'", answer: "On ne va pas être prêts à l'heure." },
          { q: "20. Form a question with 'Qu'est-ce que': What are you going to do tonight? (formal)", answer: "Qu'est-ce que vous allez faire ce soir ?" }
        ]
      },
      {
        id: "a1-futur-proche-s3",
        sheetNum: 3,
        title: "Sheet 3: Travel Plans, Schedules & Future Predictions",
        subtitle: "20 Questions · Professional agendas, trip itineraries and causal predictions",
        exercises: [
          { q: "1. Translate: 'Look at the sky, it's going to rain.'", answer: "Regarde le ciel, il va pleuvoir." },
          { q: "2. Translate: 'The plane is going to take off in ten minutes.'", answer: "L'avion va décoller dans dix minutes." },
          { q: "3. Translate: 'We are going to check in at the hotel at 3:00 PM.'", answer: "Nous allons nous enregistrer à l'hôtel à quinze heures." },
          { q: "4. Translate: 'I am going to send you the contract by email.' (formal)", answer: "Je vais vous envoyer le contrat par courriel." },
          { q: "5. Translate: 'Are you going to take the subway or a taxi?' (formal)", answer: "Allez-vous prendre le métro ou un taxi ?" },
          { q: "6. Translate: 'They are going to arrive at the airport at 18:30.'", answer: "Ils vont arriver à l'aéroport à 18h30." },
          { q: "7. Translate: 'I am not going to attend the seminar tomorrow.'", answer: "Je ne vais pas assister au séminaire demain." },
          { q: "8. Translate: 'She is going to present the quarterly budget.'", answer: "Elle va présenter le budget trimestriel." },
          { q: "9. Translate: 'We are going to spend three days in Marseille.'", answer: "Nous allons passer trois jours à Marseille." },
          { q: "10. Translate: 'Who is going to lead the team?'", answer: "Qui va diriger l'équipe ?" },
          { q: "11. Complete: Dépêchez-vous, le train ___ (partir) !", answer: "va partir" },
          { q: "12. Complete: Attention, tu ___ (tomber) !", answer: "vas tomber" },
          { q: "13. Complete: Lundi prochain, nous ___ (rencontrer) les nouveaux clients.", answer: "allons rencontrer" },
          { q: "14. Complete: Le directeur ___ (prendre) sa décision vendredi.", answer: "va prendre" },
          { q: "15. Translate: 'I am going to take a short break.'", answer: "Je vais faire une courte pause." },
          { q: "16. Translate: 'Are we going to have lunch together?'", answer: "On va déjeuner ensemble ? (or 'Allons-nous déjeuner ensemble ?')" },
          { q: "17. Translate: 'They are not going to renew the lease.'", answer: "Ils ne vont pas renouveler le bail." },
          { q: "18. Translate: 'The shop is going to close in five minutes.'", answer: "Le magasin va fermer dans cinq minutes." },
          { q: "19. Translate: 'I am going to explain the procedure.'", answer: "Je vais expliquer la procédure." },
          { q: "20. Translate: 'What are you going to order?' (in a restaurant, to partner)", answer: "Qu'est-ce que tu vas commander ?" }
        ]
      }
    ],

    "a1-reflexive-verbs": [
      {
        id: "a1-reflexive-verbs-s1",
        sheetNum: 1,
        title: "Sheet 1: Reflexive Pronouns & Present Conjugation",
        subtitle: "20 Questions · Matching me, te, se, nous, vous, se with present tense verbs",
        exercises: [
          { q: "1. What are the six reflexive pronouns corresponding to je, tu, il, nous, vous, ils?", answer: "me (m'), te (t'), se (s'), nous, vous, se (s')" },
          { q: "2. Conjugate 'se lever' with 'Je'.", answer: "Je me lève (note stem accent change)" },
          { q: "3. Conjugate 'se lever' with 'Tu'.", answer: "Tu te lèves" },
          { q: "4. Conjugate 'se lever' with 'Il'.", answer: "Il se lève" },
          { q: "5. Conjugate 'se lever' with 'Nous'.", answer: "Nous nous levons (no accent on stem)" },
          { q: "6. Conjugate 'se lever' with 'Vous'.", answer: "Vous vous levez" },
          { q: "7. Conjugate 'se lever' with 'Ils'.", answer: "Ils se lèvent" },
          { q: "8. Conjugate 's'habiller' with 'Je' (elision before h).", answer: "Je m'habille" },
          { q: "9. Conjugate 's'habiller' with 'Tu'.", answer: "Tu t'habilles" },
          { q: "10. Conjugate 's'habiller' with 'Elle'.", answer: "Elle s'habille" },
          { q: "11. Conjugate 's'habiller' with 'Nous'.", answer: "Nous nous habillons" },
          { q: "12. Conjugate 's'habiller' with 'Vous'.", answer: "Vous vous habillez" },
          { q: "13. Conjugate 's'habiller' with 'Elles'.", answer: "Elles s'habillent" },
          { q: "14. Conjugate 's'appeler' with 'Je'.", answer: "Je m'appelle (double 'l')" },
          { q: "15. Conjugate 's'appeler' with 'Nous'.", answer: "Nous nous appelons (single 'l')" },
          { q: "16. Conjugate 'se doucher' with 'Il'.", answer: "Il se douche" },
          { q: "17. Conjugate 'se raser' with 'Je'.", answer: "Je me rase" },
          { q: "18. Conjugate 'se coucher' with 'Tu'.", answer: "Tu te couches" },
          { q: "19. Conjugate 'se réveiller' with 'Nous'.", answer: "Nous nous réveillons" },
          { q: "20. Conjugate 'se dépêcher' with 'Vous'.", answer: "Vous vous dépêchez" }
        ]
      },
      {
        id: "a1-reflexive-verbs-s2",
        sheetNum: 2,
        title: "Sheet 2: Daily Routine Verbs (Morning to Night)",
        subtitle: "20 Questions · Applying reflexive verbs in a chronological workday scenario",
        exercises: [
          { q: "1. Translate: 'I wake up at 7:00 AM.'", answer: "Je me réveille à sept heures." },
          { q: "2. Translate: 'I get out of bed at 7:15.'", answer: "Je me lève à sept heures et quart." },
          { q: "3. Translate: 'He takes a shower.'", answer: "Il se douche (or 'Il prend une douche')." },
          { q: "4. Translate: 'I get dressed quickly.'", answer: "Je m'habille rapidement." },
          { q: "5. Translate: 'She brushes her teeth.'", answer: "Elle se brosse les dents. (Note: French uses 'les dents', not 'ses dents')" },
          { q: "6. Translate: 'Do you shave in the morning?' (informal)", answer: "Tu te rases le matin ?" },
          { q: "7. Translate: 'We hurry to catch the bus.'", answer: "Nous nous dépêchons pour prendre le bus." },
          { q: "8. Translate: 'He sits down at his desk.'", answer: "Il s'assied (or s'assoit) à son bureau." },
          { q: "9. Translate: 'I rest for an hour after lunch.'", answer: "Je me repose pendant une heure après le déjeuner." },
          { q: "10. Translate: 'We walk in the park on Sundays.'", answer: "Nous nous promenons dans le parc le dimanche." },
          { q: "11. Translate: 'She washes her hands.'", answer: "Elle se lave les mains." },
          { q: "12. Translate: 'What time do you go to bed?' (formal)", answer: "À quelle heure vous couchez-vous ? (or 'Vous vous couchez à quelle heure ?')" },
          { q: "13. Translate: 'I go to sleep at midnight.'", answer: "Je m'endors à minuit. (s'endormir)" },
          { q: "14. Translate: 'They (m.) remember this project.'", answer: "Ils se souviennent de ce projet." },
          { q: "15. Translate: 'Do you feel well?' (formal)", answer: "Vous vous sentez bien ?" },
          { q: "16. Translate: 'I am bored during this meeting.'", answer: "Je m'ennuie pendant cette réunion." },
          { q: "17. Translate: 'We are getting ready.'", answer: "Nous nous préparons." },
          { q: "18. Translate: 'He is mistaken / wrong.'", answer: "Il se trompe." },
          { q: "19. Translate: 'Don't worry!' (informal imperative)", answer: "Ne t'inquiète pas !" },
          { q: "20. Translate: 'Don't worry!' (formal imperative)", answer: "Ne vous inquiétez pas !" }
        ]
      },
      {
        id: "a1-reflexive-verbs-s3",
        sheetNum: 3,
        title: "Sheet 3: Negative Reflexives & Near Future Word Order",
        subtitle: "20 Questions · Sentence syntax in complex negative and infinitive constructions",
        exercises: [
          { q: "1. Where do 'ne' and 'pas' go with a reflexive verb in the present tense?", answer: "Ne precedes the reflexive pronoun, and pas follows the conjugated verb: 'Je ne me lève pas'." },
          { q: "2. Make negative: 'Je me lève tôt.'", answer: "Je ne me lève pas tôt." },
          { q: "3. Make negative: 'Tu te couches tard.'", answer: "Tu ne te couches pas tard." },
          { q: "4. Make negative: 'Il s'habille bien.'", answer: "Il ne s'habille pas bien." },
          { q: "5. Make negative: 'Nous nous dépêchons.'", answer: "Nous ne nous dépêchons pas." },
          { q: "6. Make negative: 'Vous vous souvenez.'", answer: "Vous ne vous souvenez pas." },
          { q: "7. Make negative: 'Ils se disputent.'", answer: "Ils ne se disputent pas." },
          { q: "8. In the near future (aller + inf.), where does the reflexive pronoun go?", answer: "Between aller and the infinitive, matching the subject (e.g. 'Je vais ME reposer')." },
          { q: "9. Translate into Futur Proche: 'I am going to get dressed.'", answer: "Je vais m'habiller." },
          { q: "10. Translate into Futur Proche: 'Are you going to rest?' (formal)", answer: "Allez-vous vous reposer ?" },
          { q: "11. Translate into Futur Proche: 'She is going to wake up at 8:00.'", answer: "Elle va se réveiller à huit heures." },
          { q: "12. Translate into Futur Proche: 'We are not going to hurry.'", answer: "Nous n'allons pas nous dépêcher." },
          { q: "13. Translate into Futur Proche: 'They are going to walk.'", answer: "Ils vont se promener." },
          { q: "14. Correct the error: 'Je vais me laver les dents.' (Vocabulary precision)", answer: "Correction: 'Je vais me BROSSER les dents.' (se laver is used for body/hands, brosser for teeth/hair)" },
          { q: "15. Correct the error: 'Je ne lève pas me tôt.'", answer: "Correction: 'Je ne me lève pas tôt.'" },
          { q: "16. Correct the error: 'Nous allons reposer nous.'", answer: "Correction: 'Nous allons nous reposer.'" },
          { q: "17. Translate: 'I need to shave.'", answer: "Je dois me raser (or 'J'ai besoin de me raser')." },
          { q: "18. Translate: 'Do you want to sit down?' (formal)", answer: "Voulez-vous vous asseoir ?" },
          { q: "19. Make negative: 'Elle s'intéresse à l'art.'", answer: "Elle ne s'intéresse pas à l'art." },
          { q: "20. Form the affirmative imperative: 'Hurry up!' (informal)", answer: "Dépêche-toi ! (Note: te becomes toi in affirmative imperative)" }
        ]
      }
    ],

    "a1-possessive-adjectives": [
      {
        id: "a1-possessive-adjectives-s1",
        sheetNum: 1,
        title: "Sheet 1: Mon, Ma, Mes / Ton, Ta, Tes System",
        subtitle: "20 Questions · Singular and plural possessives for 1st and 2nd person",
        exercises: [
          { q: "1. What are the three forms of 'my' in French?", answer: "mon (m. sing.), ma (f. sing.), mes (pl.)" },
          { q: "2. What are the three forms of 'your' (informal, tu)?", answer: "ton (m. sing.), ta (f. sing.), tes (pl.)" },
          { q: "3. Fill in 'my': ___ passeport (m.).", answer: "mon passeport" },
          { q: "4. Fill in 'my': ___ valise (f.).", answer: "ma valise" },
          { q: "5. Fill in 'my': ___ clés (pl.).", answer: "mes clés" },
          { q: "6. Fill in 'your' (informal): ___ billet (m.).", answer: "ton billet" },
          { q: "7. Fill in 'your' (informal): ___ chambre (f.).", answer: "ta chambre" },
          { q: "8. Fill in 'your' (informal): ___ bagages (pl.).", answer: "tes bagages" },
          { q: "9. Fill in 'my': ___ ordinateur (m.).", answer: "mon ordinateur" },
          { q: "10. Fill in 'my': ___ adresse (f. starting with vowel — special rule!).", answer: "mon adresse (mon replaces ma before feminine nouns starting with a vowel)" },
          { q: "11. Fill in 'my': ___ amie (f. starting with vowel).", answer: "mon amie" },
          { q: "12. Fill in 'your' (informal): ___ entreprise (f. starting with vowel).", answer: "ton entreprise (ton replaces ta before a vowel)" },
          { q: "13. Fill in 'your' (informal): ___ idée (f. starting with vowel).", answer: "ton idée" },
          { q: "14. Translate: 'My parents live in Bordeaux.'", answer: "Mes parents habitent à Bordeaux." },
          { q: "15. Translate: 'Where is your car?' (informal)", answer: "Où est ta voiture ?" },
          { q: "16. Translate: 'I like your style.' (informal)", answer: "J'aime ton style." },
          { q: "17. Translate: 'My brother and my sister.'", answer: "Mon frère et ma sœur." },
          { q: "18. Translate: 'My colleagues are competent.' (m. pl.)", answer: "Mes collègues sont compétents." },
          { q: "19. In French, does the possessive adjective agree with the owner or the possessed item?", answer: "With the POSSESSED ITEM (its gender and number), NOT the owner." },
          { q: "20. Complete: J'ai oublié ___ montre (f.) à l'hôtel.", answer: "ma montre" }
        ]
      },
      {
        id: "a1-possessive-adjectives-s2",
        sheetNum: 2,
        title: "Sheet 2: Son, Sa, Ses & Plural Possessives (Notre, Votre, Leur)",
        subtitle: "20 Questions · Third-person and group possessive determiners",
        exercises: [
          { q: "1. What are the three forms of 'his / her / its' in French?", answer: "son (m. sing.), sa (f. sing.), ses (pl.)" },
          { q: "2. Translate 'his car' (Pierre's car).", answer: "sa voiture (feminine noun takes 'sa', regardless of Pierre being male!)" },
          { q: "3. Translate 'her book' (Marie's book).", answer: "son livre (masculine noun takes 'son', regardless of Marie being female!)" },
          { q: "4. Translate 'his keys' and 'her keys'.", answer: "ses clés (identical in both cases!)" },
          { q: "5. What are the forms of 'our' in French?", answer: "notre (singular: m. & f.), nos (plural)" },
          { q: "6. What are the forms of 'your' (formal / plural vous)?", answer: "votre (singular: m. & f.), vos (plural)" },
          { q: "7. What are the forms of 'their' in French?", answer: "leur (singular: m. & f.), leurs (plural with -s)" },
          { q: "8. Fill in 'our': ___ appartement (m.).", answer: "notre appartement" },
          { q: "9. Fill in 'our': ___ maison (f.).", answer: "notre maison" },
          { q: "10. Fill in 'our': ___ enfants (pl.).", answer: "nos enfants" },
          { q: "11. Fill in 'your' (formal): ___ passeport (m.).", answer: "votre passeport" },
          { q: "12. Fill in 'your' (formal): ___ signature (f.).", answer: "votre signature" },
          { q: "13. Fill in 'your' (formal): ___ coordonnées (pl.).", answer: "vos coordonnées" },
          { q: "14. Fill in 'their': ___ projet (m.).", answer: "leur projet" },
          { q: "15. Fill in 'their': ___ équipe (f.).", answer: "leur équipe" },
          { q: "16. Fill in 'their': ___ clients (pl.).", answer: "leurs clients" },
          { q: "17. Translate: 'They are looking for their dog.'", answer: "Ils cherchent leur chien." },
          { q: "18. Translate: 'They are looking for their keys.'", answer: "Ils cherchent leurs clés." },
          { q: "19. Fill in: Marie parle avec ___ collègue (m.).", answer: "son collègue" },
          { q: "20. Fill in: Paul voyage avec ___ femme (f.).", answer: "sa femme" }
        ]
      },
      {
        id: "a1-possessive-adjectives-s3",
        sheetNum: 3,
        title: "Sheet 3: Feminine Vowel Shift & Contextual Mastery",
        subtitle: "20 Questions · Phonetic vowel shifts (mon amie) and authentic communicative usage",
        exercises: [
          { q: "1. Why does one say 'mon amie' instead of 'ma amie'?", answer: "To avoid hiatus (the clash of two consecutive spoken vowel sounds: [ma-a-mee])." },
          { q: "2. Fill in 'his' for 'opinion' (f.): ___ opinion.", answer: "son opinion" },
          { q: "3. Fill in 'your' (inf.) for 'histoire' (f.): ___ histoire.", answer: "ton histoire (h muet acts as a vowel)" },
          { q: "4. Fill in 'her' for 'erreur' (f.): ___ erreur.", answer: "son erreur" },
          { q: "5. Fill in 'my' for 'ancienne école' (f.): ___ ancienne école.", answer: "mon ancienne école (adjective starts with vowel)" },
          { q: "6. Translate: 'Please leave your keys at reception.' (formal)", answer: "Veuillez laisser vos clés à la réception." },
          { q: "7. Translate: 'Our train arrives at 16:15.'", answer: "Notre train arrive à seize heures quinze." },
          { q: "8. Translate: 'Is this your jacket, sir?'", answer: "C'est votre veste, monsieur ?" },
          { q: "9. Translate: 'Sophie introduced her husband to her director.'", answer: "Sophie a présenté son mari à son directeur." },
          { q: "10. Correct the error: 'C'est sa ami.'", answer: "Correction: 'C'est son ami(e).' (son before vowel)" },
          { q: "11. Correct the error: 'Leur valises sont ici.'", answer: "Correction: 'Leurs valises sont ici.' (plural noun requires leurs)" },
          { q: "12. Correct the error: 'Pierre aime son mère.'", answer: "Correction: 'Pierre aime sa mère.' (mère is feminine, takes sa)" },
          { q: "13. Translate: 'We love our country.'", answer: "Nous aimons notre pays." },
          { q: "14. Translate: 'They invited their friends to dinner.'", answer: "Ils ont invité leurs amis à dîner." },
          { q: "15. Translate: 'What is your email address?' (formal)", answer: "Quelle est votre adresse électronique (or courriel) ?" },
          { q: "16. Translate: 'I need your help.' (informal)", answer: "J'ai besoin de ton aide." },
          { q: "17. Translate: 'His boss is demanding.' (m.)", answer: "Son patron est exigeant." },
          { q: "18. Translate: 'Her boss is demanding.' (m.)", answer: "Son patron est exigeant. (same wording in French)" },
          { q: "19. Complete with possessive: Les enfants ont fini ___ devoirs.", answer: "leurs devoirs" },
          { q: "20. Complete: Vous avez oublié ___ parapluie (m.) dans le taxi.", answer: "votre parapluie" }
        ]
      }
    ],

    "a1-partitive-articles": [
      {
        id: "a1-partitive-articles-s1",
        sheetNum: 1,
        title: "Sheet 1: Du, De la, De l', Des vs. Definite Articles",
        subtitle: "20 Questions · Specifying uncountable quantities of food, drinks and substances",
        exercises: [
          { q: "1. What is the masculine singular partitive article?", answer: "du (contraction of de + le)" },
          { q: "2. What is the feminine singular partitive article?", answer: "de la" },
          { q: "3. What is the partitive article before a vowel or silent h (m. or f.)?", answer: "de l'" },
          { q: "4. What is the plural partitive article (for plural uncountables/staples)?", answer: "des" },
          { q: "5. Fill in the partitive: Je bois ___ café (m.).", answer: "du café" },
          { q: "6. Fill in the partitive: Elle mange ___ salade (f.).", answer: "de la salade" },
          { q: "7. Fill in the partitive: Nous buvons ___ eau (f. vowel).", answer: "de l'eau" },
          { q: "8. Fill in the partitive: Il achète ___ pain (m.).", answer: "du pain" },
          { q: "9. Fill in the partitive: Tu prends ___ beurre (m.) ?", answer: "du beurre" },
          { q: "10. Fill in the partitive: Je voudrais ___ confiture (f.).", answer: "de la confiture" },
          { q: "11. Fill in the partitive: Ajoutez ___ huile d'olive (f. vowel).", answer: "de l'huile d'olive" },
          { q: "12. Fill in the partitive: Nous mangeons ___ pâtes (pl.).", answer: "des pâtes" },
          { q: "13. Contrast: 'J'aime le fromage' vs. 'Je mange du fromage'. What is the difference?", answer: "'J'aime le fromage' expresses a general preference (all cheese); 'Je mange du fromage' expresses an unspecified quantity consumed." },
          { q: "14. Complete with definite or partitive: Elle adore ___ chocolat (general taste).", answer: "le chocolat" },
          { q: "15. Complete: Elle mange ___ chocolat tous les soirs (quantity).", answer: "du chocolat" },
          { q: "16. Complete: Il déteste ___ vin rouge.", answer: "le vin rouge" },
          { q: "17. Complete: Il commande ___ vin rouge pour le dîner.", answer: "du vin rouge" },
          { q: "18. Fill in the partitive: Il faut ___ patience (f.).", answer: "de la patience" },
          { q: "19. Fill in the partitive: Ce travail demande ___ énergie (f. vowel).", answer: "de l'énergie" },
          { q: "20. Fill in the partitive: Le musicien a ___ talent (m.).", answer: "du talent" }
        ]
      },
      {
        id: "a1-partitive-articles-s2",
        sheetNum: 2,
        title: "Sheet 2: Negation Rules (De / D' replacing Partitives)",
        subtitle: "20 Questions · Applying the rule of absolute negation with quantities",
        exercises: [
          { q: "1. What do du, de la, de l', and des become in a negative sentence?", answer: "'de' (or 'd'' before a vowel or silent h)" },
          { q: "2. Make negative: 'Je bois du café.'", answer: "Je ne bois pas de café." },
          { q: "3. Make negative: 'Elle mange de la viande.'", answer: "Elle ne mange pas de viande." },
          { q: "4. Make negative: 'Nous buvons de l'alcool.'", answer: "Nous ne buvons pas d'alcool." },
          { q: "5. Make negative: 'Il prend du sucre.'", answer: "Il ne prend pas de sucre." },
          { q: "6. Make negative: 'J'ai de la monnaie.'", answer: "Je n'ai pas de monnaie." },
          { q: "7. Make negative: 'Il y a du soleil aujourd'hui.'", answer: "Il n'y a pas de soleil aujourd'hui." },
          { q: "8. Make negative: 'Nous avons de l'eau gazeuse.'", answer: "Nous n'avons pas d'eau gazeuse." },
          { q: "9. Make negative: 'Ils achètent des œufs.'", answer: "Ils n'achètent pas d'œufs." },
          { q: "10. Make negative: 'Tu manges des légumes.'", answer: "Tu ne manges pas de légumes." },
          { q: "11. After adverbs of quantity (beaucoup, peu, trop), what preposition is used instead of partitives?", answer: "'de' (or 'd'') — e.g. beaucoup de pain, un peu de sucre." },
          { q: "12. Fill in: Je voudrais un peu ___ sel, s'il vous plaît.", answer: "de sel" },
          { q: "13. Fill in: Il boit beaucoup ___ eau.", answer: "d'eau" },
          { q: "14. Fill in: Il y a trop ___ sucre dans ce gâteau.", answer: "de sucre" },
          { q: "15. Fill in: Elle a assez ___ temps pour finir.", answer: "de temps" },
          { q: "16. Fill in: Nous achetons un kilo ___ pommes.", answer: "de pommes" },
          { q: "17. Fill in: Une bouteille ___ vin.", answer: "de vin" },
          { q: "18. Fill in: Une tasse ___ thé.", answer: "de thé" },
          { q: "19. Correct the error: 'Je ne veux pas du fromage.'", answer: "Correction: 'Je ne veux pas DE fromage.'" },
          { q: "20. Correct the error: 'Il a beaucoup des amis.'", answer: "Correction: 'Il a beaucoup D'amis.'" }
        ]
      },
      {
        id: "a1-partitive-articles-s3",
        sheetNum: 3,
        title: "Sheet 3: Cooking Recipes, Restaurant Orders & Quantities",
        subtitle: "20 Questions · Practical gastronomy, ordering food and following recipe instructions",
        exercises: [
          { q: "1. Translate: 'I would like some bread and butter, please.'", answer: "Je voudrais du pain et du beurre, s'il vous plaît." },
          { q: "2. Translate: 'Do you take milk in your coffee?' (formal)", answer: "Prenez-vous du lait dans votre café ?" },
          { q: "3. Translate: 'We need flour, eggs and milk for the crêpes.'", answer: "Il nous faut de la farine, des œufs et du lait pour les crêpes." },
          { q: "4. Translate: 'Add a glass of white wine.'", answer: "Ajoutez un verre de vin blanc." },
          { q: "5. Translate: 'There is no salt on the table.'", answer: "Il n'y a pas de sel sur la table." },
          { q: "6. Translate: 'Do you have tap water?' (carafe d'eau)", answer: "Avez-vous une carafe d'eau ?" },
          { q: "7. Translate: 'I don't eat meat; I am a vegetarian.' (m.)", answer: "Je ne mange pas de viande ; je suis végétarien." },
          { q: "8. Translate: 'Can you bring some ice cubes?'", answer: "Pouvez-vous apporter des glaçons ?" },
          { q: "9. Translate: 'Put some mustard on the sandwich.'", answer: "Mettez de la moutarde sur le sandwich." },
          { q: "10. Translate: 'A slice of ham and some cheese.'", answer: "Une tranche de jambon et du fromage." },
          { q: "11. Fill in: Pour faire cette sauce, il faut ___ ail (m. vowel) et ___ herbes (f. pl.).", answer: "de l'ail et des herbes" },
          { q: "12. Fill in: Vous désirez ___ dessert (m.) ?", answer: "un dessert (or du dessert)" },
          { q: "13. Fill in: Donnez-moi 250 grammes ___ beurre.", answer: "de beurre" },
          { q: "14. Fill in: Est-ce qu'il reste ___ café dans la cafetière ?", answer: "du café" },
          { q: "15. Fill in: Non, il ne reste plus ___ café.", answer: "de café (ne... plus de)" },
          { q: "16. Translate: 'She drinks tea without sugar.'", answer: "Elle boit du thé sans sucre." },
          { q: "17. Translate: 'Do you have fresh fruit?'", answer: "Avez-vous des fruits frais ?" },
          { q: "18. Translate: 'Buy a loaf of bread and two baguettes.'", answer: "Achète un pain et deux baguettes." },
          { q: "19. Translate: 'We eat fish on Fridays.'", answer: "Nous mangeons du poisson le vendredi." },
          { q: "20. Translate: 'How much cheese do you want?'", answer: "Combien de fromage voulez-vous ?" }
        ]
      }
    ]
  };

  root.GRAMMAR_A1_EXT_WORKSHEETS = grammarA1ExtWorksheets;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = grammarA1ExtWorksheets;
  }
})(typeof window !== "undefined" ? window : globalThis);
