(function (root) {
  const grammarA2Worksheets = {
    "a2-relative-pronouns-qui-que": [
      {
        id: "a2-relative-pronouns-qui-que-s1",
        sheetNum: 1,
        title: "Sheet 1: Syntactic Role: Qui (Subject) vs. Que (Direct Object)",
        subtitle: "20 Questions · Structural distinction between subject and object relative clauses",
        exercises: [
          { q: "1. What grammatical role does 'qui' play in the relative clause?", answer: "Subject of the dependent verb (followed directly by a conjugated verb or reflexive pronoun)." },
          { q: "2. What grammatical role does 'que' play in the relative clause?", answer: "Direct object (COD) of the dependent verb (followed by a subject + verb)." },
          { q: "3. Does 'que' elide to 'qu'' before a vowel? Does 'qui' ever elide?", answer: "'Que' becomes 'qu'' before a vowel; 'qui' NEVER elides (e.g. 'l'homme qui arrive', never 'qu'arrive')." },
          { q: "4. Fill in: L'homme ___ parle avec le directeur est mon collègue.", answer: "qui (qui parle — subject of parle)" },
          { q: "5. Fill in: Le rapport ___ j'ai rédigé est sur le bureau.", answer: "que (que j'ai rédigé — object of ai rédigé)" },
          { q: "6. Fill in: L'ordinateur ___ ne fonctionne pas doit être réparé.", answer: "qui (qui ne fonctionne pas — subject)" },
          { q: "7. Fill in: La ville ___ nous visitons est magnifique.", answer: "que (que nous visitons — object)" },
          { q: "8. Fill in: Les dossiers ___ sont archivés se trouvent au sous-sol.", answer: "qui (qui sont archivés — subject)" },
          { q: "9. Fill in: C'est l'étudiant ___ a obtenu la meilleure note.", answer: "qui" },
          { q: "10. Fill in: C'est le livre ___ elle lit en ce moment.", answer: "que" },
          { q: "11. Fill in: L'hôtel ___ il a réservé est complet.", answer: "qu' (qu'il a réservé — elision before il)" },
          { q: "12. Fill in: L'avocat ___ nous conseille est réputé.", answer: "qui (qui nous conseille — subject of conseille; 'nous' is object pronoun)" },
          { q: "13. Fill in: Les collègues ___ m'aident sont sympathiques.", answer: "qui (qui m'aident — subject)" },
          { q: "14. Fill in: Le train ___ part à 18h est direct.", answer: "qui" },
          { q: "15. Fill in: Le train ___ nous prenons a dix minutes de retard.", answer: "que" },
          { q: "16. Fill in: Voici le document ___ tu as demandé hier.", answer: "que" },
          { q: "17. Fill in: C'est une décision ___ va changer nos projets.", answer: "qui" },
          { q: "18. Fill in: Les photos ___ vous avez prises sont superbes.", answer: "que (qu'elles ont prises)" },
          { q: "19. Fill in: La femme ___ habite à côté est médecin.", answer: "qui" },
          { q: "20. Fill in: Les cours ___ elle suit sont passionnants.", answer: "que" }
        ]
      },
      {
        id: "a2-relative-pronouns-qui-que-s2",
        sheetNum: 2,
        title: "Sheet 2: Past Participle Agreement with Preceding 'Que'",
        subtitle: "20 Questions · Mastering participle agreement when 'que' represents a preceding direct object",
        exercises: [
          { q: "1. When does the past participle agree with 'que'?", answer: "When 'que' represents a preceding direct object in compound tenses with avoir (agreement in gender and number)." },
          { q: "2. Form participle: La lettre que j'ai (écrire) ___.", answer: "écrite (lettre is f. sing., preceding COD)" },
          { q: "3. Form participle: Les fleurs qu'il a (acheter) ___.", answer: "achetées (f. pl.)" },
          { q: "4. Form participle: Le contrat qu'ils ont (signer) ___.", answer: "signé (m. sing.)" },
          { q: "5. Form participle: Les rapports qu'elle a (rédiger) ___.", answer: "rédigés (m. pl.)" },
          { q: "6. Form participle: La maison que nous avons (vendre) ___.", answer: "vendue (f. sing.)" },
          { q: "7. Form participle: Les erreurs que vous avez (commettre) ___.", answer: "commises (f. pl.)" },
          { q: "8. Form participle: La décision qui a été (prendre) ___.", answer: "prise (passive with être agrees with subject)" },
          { q: "9. Does participle agree with 'qui' in: 'La femme qui a parlé'?", answer: "NO. 'Qui' is subject with avoir, so there is no preceding direct object: 'a parlé'." },
          { q: "10. Choose correct: La clé que j'ai (trouvé / trouvée).", answer: "trouvée" },
          { q: "11. Choose correct: Les valises qu'ils ont (oublié / oubliées).", answer: "oubliées" },
          { q: "12. Choose correct: Les messages que tu as (reçu / reçus).", answer: "reçus" },
          { q: "13. Choose correct: La facture qu'elle a (payé / payée).", answer: "payée" },
          { q: "14. Choose correct: L'offre d'emploi qu'il a (accepté / acceptée).", answer: "acceptée (offre is feminine)" },
          { q: "15. Choose correct: Les explications qui m'ont (aidé / aidée / aidés).", answer: "aidé (no preceding COD agreement with avoir when object follows verb)" },
          { q: "16. Correct the error: 'Les lettres que tu as envoyé ce matin.'", answer: "Correction: 'Les lettres que tu as ENVOYÉES ce matin.'" },
          { q: "17. Correct the error: 'C'est l'homme qu'habite ici.'", answer: "Correction: 'C'est l'homme QUI habite ici.' (qui never elides)" },
          { q: "18. Correct the error: 'La robe que elle a achetée.'", answer: "Correction: 'La robe QU'ELLE a achetée.' (que must elide)" },
          { q: "19. Form participle: Les questions que vous avez (poser) ___.", answer: "posées" },
          { q: "20. Form participle: La solution qu'on a (proposer) ___.", answer: "proposée" }
        ]
      },
      {
        id: "a2-relative-pronouns-qui-que-s3",
        sheetNum: 3,
        title: "Sheet 3: Combining Clauses & Contextual Complex Sentences",
        subtitle: "20 Questions · Merging independent sentences into coherent complex discourse",
        exercises: [
          { q: "1. Combine into one sentence using QUI: 'J'ai un ami. Cet ami habite à Genève.'", answer: "J'ai un ami qui habite à Genève." },
          { q: "2. Combine using QUE: 'Voici le rapport. Le client attend ce rapport.'", answer: "Voici le rapport que le client attend." },
          { q: "3. Combine using QUI: 'Nous avons rencontré une cliente. Elle parle quatre langues.'", answer: "Nous avons rencontré une cliente qui parle quatre langues." },
          { q: "4. Combine using QU': 'Où sont les dossiers ? J'ai préparé ces dossiers.'", answer: "Où sont les dossiers que j'ai préparés ?" },
          { q: "5. Combine using QUI: 'C'est une entreprise innovante. Elle recrute beaucoup d'ingénieurs.'", answer: "C'est une entreprise innovante qui recrute beaucoup d'ingénieurs." },
          { q: "6. Translate: 'The person who called you left a message.'", answer: "La personne qui vous a appelé(e) a laissé un message." },
          { q: "7. Translate: 'The apartment that we visited is too small.'", answer: "L'appartement que nous avons visité est trop petit." },
          { q: "8. Translate: 'I know someone who can help you.'", answer: "Je connais quelqu'un qui peut vous aider." },
          { q: "9. Translate: 'Where is the restaurant that you recommended?'", answer: "Où est le restaurant que tu as recommandé (or que vous avez recommandé) ?" },
          { q: "10. Translate: 'The project which was approved starts next week.'", answer: "Le projet qui a été approuvé commence la semaine prochaine." },
          { q: "11. Fill in qui or que: Ce sont des détails ___ ne changent rien.", answer: "qui" },
          { q: "12. Fill in qui or que: Ce sont des détails ___ j'avais oubliés.", answer: "que" },
          { q: "13. Fill in qui or que: L'ingénieur ___ dirige le chantier est très exigeant.", answer: "qui" },
          { q: "14. Fill in qui or que: L'ingénieur ___ nous avons embauché a beaucoup d'expérience.", answer: "que" },
          { q: "15. Translate: 'The problem that worries me is the deadline.'", answer: "Le problème qui m'inquiète, c'est le délai." },
          { q: "16. Translate: 'The presentation that she delivered was clear.'", answer: "La présentation qu'elle a faite était claire." },
          { q: "17. Identify whether the relative pronoun is subject or object: 'Les enfants qui jouent dehors.'", answer: "Subject (qui)" },
          { q: "18. Identify whether subject or object: 'Les devoirs que le professeur donne.'", answer: "Object (que)" },
          { q: "19. Combine: 'J'aime cette ville. Cette ville offre beaucoup d'activités culturelles.'", answer: "J'aime cette ville qui offre beaucoup d'activités culturelles." },
          { q: "20. Combine: 'C'est un travail difficile. Je dois terminer ce travail avant midi.'", answer: "C'est un travail difficile que je dois terminer avant midi." }
        ]
      }
    ],

    "a2-passe-compose-avoir": [
      {
        id: "a2-passe-compose-avoir-s1",
        sheetNum: 1,
        title: "Sheet 1: Past Participle Formations (-é, -i, -u, irregulars)",
        subtitle: "20 Questions · Regular and high-frequency irregular past participle morphology",
        exercises: [
          { q: "1. What is the regular past participle ending for -ER verbs (e.g. parler)?", answer: "-é (parlé)" },
          { q: "2. What is the regular past participle ending for regular -IR verbs (e.g. finir)?", answer: "-i (fini)" },
          { q: "3. What is the past participle of 'choisir'?", answer: "choisi" },
          { q: "4. What is the past participle of 'vendre' (regular -RE)?", answer: "vendu" },
          { q: "5. What is the past participle of 'attendre'?", answer: "attendu" },
          { q: "6. What is the past participle of 'avoir'?", answer: "eu [ew]" },
          { q: "7. What is the past participle of 'être'?", answer: "été" },
          { q: "8. What is the past participle of 'faire'?", answer: "fait" },
          { q: "9. What is the past participle of 'prendre'?", answer: "pris" },
          { q: "10. What is the past participle of 'apprendre'?", answer: "appris" },
          { q: "11. What is the past participle of 'comprendre'?", answer: "compris" },
          { q: "12. What is the past participle of 'mettre'?", answer: "mis" },
          { q: "13. What is the past participle of 'dire'?", answer: "dit" },
          { q: "14. What is the past participle of 'écrire'?", answer: "écrit" },
          { q: "15. What is the past participle of 'voir'?", answer: "vu" },
          { q: "16. What is the past participle of 'boire'?", answer: "bu" },
          { q: "17. What is the past participle of 'lire'?", answer: "lu" },
          { q: "18. What is the past participle of 'pouvoir'?", answer: "pu" },
          { q: "19. What is the past participle of 'vouloir'?", answer: "voulu" },
          { q: "20. What is the past participle of 'devoir'?", answer: "dû (with circumflex accent on masculine singular)" }
        ]
      },
      {
        id: "a2-passe-compose-avoir-s2",
        sheetNum: 2,
        title: "Sheet 2: Sentence Conjugation & Negation in Passé Composé",
        subtitle: "20 Questions · Complete sentence formation, negative framing, and adverb placement",
        exercises: [
          { q: "1. Conjugate in Passé Composé: Je (parler) avec le directeur.", answer: "J'ai parlé avec le directeur." },
          { q: "2. Conjugate: Tu (finir) le travail ?", answer: "Tu as fini le travail ?" },
          { q: "3. Conjugate: Il (prendre) le train de 8h.", answer: "Il a pris le train de 8h." },
          { q: "4. Conjugate: Nous (faire) une réservation.", answer: "Nous avons fait une réservation." },
          { q: "5. Conjugate: Vous (avoir) mon message ?", answer: "Vous avez eu mon message ?" },
          { q: "6. Conjugate: Ils (voir) la nouvelle proposition.", answer: "Ils ont vu la nouvelle proposition." },
          { q: "7. Where do 'ne' and 'pas' go in the Passé Composé?", answer: "Around the auxiliary verb: 'ne [avoir] pas [participe passé]'." },
          { q: "8. Make negative: 'J'ai compris.'", answer: "Je n'ai pas compris." },
          { q: "9. Make negative: 'Il a signé le contrat.'", answer: "Il n'a pas signé le contrat." },
          { q: "10. Make negative: 'Nous avons reçu la réponse.'", answer: "Nous n'avons pas reçu la réponse." },
          { q: "11. Where do short adverbs like 'bien', 'mal', 'déjà', 'beaucoup' go in Passé Composé?", answer: "Between the auxiliary and past participle (e.g. 'J'ai bien mangé', 'Il a déjà fini')." },
          { q: "12. Translate: 'I have already finished.'", answer: "J'ai déjà fini." },
          { q: "13. Translate: 'We ate very well.'", answer: "Nous avons très bien mangé." },
          { q: "14. Translate: 'She worked a lot yesterday.'", answer: "Elle a beaucoup travaillé hier." },
          { q: "15. Form an inverted question: 'Vous avez lu ce document.'", answer: "Avez-vous lu ce document ?" },
          { q: "16. Form an inverted question: 'Il a téléphoné.' (with euphonic -t-)", answer: "A-t-il téléphoné ?" },
          { q: "17. Make negative: 'Ils ont bu du café.'", answer: "Ils n'ont pas bu de café. (partitive becomes de)" },
          { q: "18. Make negative: 'J'ai acheté des timbres.'", answer: "Je n'ai pas acheté de timbres." },
          { q: "19. Translate: 'Did you sleep well?' (informal)", answer: "Tu as bien dormi ?" },
          { q: "20. Translate: 'I didn't hear anything.' (ne... rien)", answer: "Je n'ai rien entendu. ('rien' replaces 'pas' between auxiliary and participle)" }
        ]
      },
      {
        id: "a2-passe-compose-avoir-s3",
        sheetNum: 3,
        title: "Sheet 3: Workplace & Travel Recounts",
        subtitle: "20 Questions · Contextual storytelling of completed past actions",
        exercises: [
          { q: "1. Translate: 'Yesterday, I met a client in Montparnasse.'", answer: "Hier, j'ai rencontré un client à Montparnasse." },
          { q: "2. Translate: 'We discussed the new product line.'", answer: "Nous avons discuté de la nouvelle gamme de produits." },
          { q: "3. Translate: 'She answered all the emails this morning.'", answer: "Elle a répondu à tous les courriels ce matin." },
          { q: "4. Translate: 'I lost my keys at the station.'", answer: "J'ai perdu mes clés à la gare." },
          { q: "5. Translate: 'Did you pay by credit card?' (formal)", answer: "Avez-vous payé par carte bancaire ?" },
          { q: "6. Translate: 'The flight cost €240.'", answer: "Le vol a coûté deux cent quarante euros." },
          { q: "7. Translate: 'They (m.) decided to postpone the launch.'", answer: "Ils ont décidé de reporter le lancement." },
          { q: "8. Translate: 'I didn't have time to prepare the slides.'", answer: "Je n'ai pas eu le temps de préparer les diapositives." },
          { q: "9. Translate: 'We visited three apartments before choosing.'", answer: "Nous avons visité trois appartements avant de choisir." },
          { q: "10. Translate: 'Who organized this event?'", answer: "Qui a organisé cet événement ?" },
          { q: "11. Conjugate: Les avocats (examiner) ___ le dossier.", answer: "ont examiné" },
          { q: "12. Conjugate: Tu (écrire) ___ au service client ?", answer: "as écrit" },
          { q: "13. Conjugate: Le comptable (vérifier) ___ les factures.", answer: "a vérifié" },
          { q: "14. Translate: 'I drank a glass of water.'", answer: "J'ai bu un verre d'eau." },
          { q: "15. Translate: 'She received a delivery.'", answer: "Elle a reçu une livraison." },
          { q: "16. Translate: 'We opened an account.'", answer: "Nous avons ouvert un compte." },
          { q: "17. What is the past participle of 'ouvrir'?", answer: "ouvert" },
          { q: "18. What is the past participle of 'offrir'?", answer: "offert" },
          { q: "19. Translate: 'He offered a gift to his colleague.'", answer: "Il a offert un cadeau à son collègue." },
          { q: "20. Translate: 'I spent two hours at the bank.'", answer: "J'ai passé deux heures à la banque. (passer du temps takes avoir)" }
        ]
      }
    ],

    "a2-passe-compose-etre": [
      {
        id: "a2-passe-compose-etre-s1",
        sheetNum: 1,
        title: "Sheet 1: The Movement & State Verbs ('Maison d'Être')",
        subtitle: "20 Questions · Identifying the 14-16 core intransitive verbs conjugated with être",
        exercises: [
          { q: "1. Name the mnemonic house of movement verbs conjugated with être in French.", answer: "La Maison d'Être (DR MRS VANDERTRAMP verbs)" },
          { q: "2. What is the past participle of 'aller'?", answer: "allé" },
          { q: "3. What is the past participle of 'venir'?", answer: "venu" },
          { q: "4. What is the past participle of 'arriver'?", answer: "arrivé" },
          { q: "5. What is the past participle of 'partir'?", answer: "parti" },
          { q: "6. What is the past participle of 'entrer'?", answer: "entré" },
          { q: "7. What is the past participle of 'sortir'?", answer: "sorti" },
          { q: "8. What is the past participle of 'monter'?", answer: "monté" },
          { q: "9. What is the past participle of 'descendre'?", answer: "descendu" },
          { q: "10. What is the past participle of 'naître'?", answer: "né" },
          { q: "11. What is the past participle of 'mourir'?", answer: "mort" },
          { q: "12. What is the past participle of 'tomber'?", answer: "tombé" },
          { q: "13. What is the past participle of 'rester'?", answer: "resté" },
          { q: "14. What is the past participle of 'retourner'?", answer: "retourné" },
          { q: "15. What is the past participle of 'passer' (when meaning 'to pass by/through')?", answer: "passé (with être when intransitive: 'je suis passé par Lyon')" },
          { q: "16. Are all reflexive verbs (se lever, se coucher) conjugated with avoir or être?", answer: "Always with ÊTRE in compound tenses." },
          { q: "17. What auxiliary does 'rentrer' take?", answer: "ÊTRE (e.g. Je suis rentré à la maison)." },
          { q: "18. What auxiliary does 'revenir' take?", answer: "ÊTRE (e.g. Il est revenu hier)." },
          { q: "19. What auxiliary does 'devenir' take?", answer: "ÊTRE (e.g. Elle est devenue directrice)." },
          { q: "20. Does 'marcher' (to walk) take avoir or être?", answer: "AVOIR (J'ai marché — marcher is not in the Maison d'Être!)." }
        ]
      },
      {
        id: "a2-passe-compose-etre-s2",
        sheetNum: 2,
        title: "Sheet 2: Mandatory Subject-Participle Agreement",
        subtitle: "20 Questions · Adding -e for feminine and -s for plural with être auxiliaries",
        exercises: [
          { q: "1. What is the mandatory agreement rule for verbs conjugated with ÊTRE in Passé Composé?", answer: "The past participle MUST agree in gender and number with the SUBJECT." },
          { q: "2. Form agreement: Marie est (partir) ___ à midi.", answer: "partie (feminine singular adds -e)" },
          { q: "3. Form agreement: Pierre et Paul sont (arriver) ___ ensemble.", answer: "arrivés (masculine plural adds -s)" },
          { q: "4. Form agreement: Sophie et Julie sont (venir) ___ en train.", answer: "venues (feminine plural adds -es)" },
          { q: "5. Form agreement: Je suis (naître) ___ en 1990 (spoken by a woman).", answer: "née" },
          { q: "6. Form agreement: Nous sommes (rester) ___ à l'hôtel (group of women).", answer: "restées" },
          { q: "7. Form agreement: Vous êtes (entrer) ___ par quelle porte ? (formal to one gentleman)", answer: "entré (singular masculine — no -s when vous addresses one person)" },
          { q: "8. Form agreement: Vous êtes (entrer) ___ par quelle porte ? (formal to one lady)", answer: "entrée (singular feminine adds -e)" },
          { q: "9. Form agreement: Ils sont (monter) ___ au cinquième étage.", answer: "montés" },
          { q: "10. Form agreement: Elle est (descendre) ___ du taxi.", answer: "descendue" },
          { q: "11. Form agreement: Il est (tomber) ___ dans les escaliers.", answer: "tombé" },
          { q: "12. Form agreement: Les déléguées sont (retourner) ___ à Genève.", answer: "retournées" },
          { q: "13. Form agreement: Mes cousines sont (mourir) ___ à un âge avancé.", answer: "mortes" },
          { q: "14. Form agreement: Elle s'est (lever) ___ à 6h30.", answer: "levée (reflexive verb agrees with subject when subject is COD)" },
          { q: "15. Form agreement: Ils se sont (dépêcher) ___ pour ne pas rater le vol.", answer: "dépêchés" },
          { q: "16. Correct the error: 'Elle est allé au bureau.'", answer: "Correction: 'Elle est ALLÉE au bureau.' (agreement with elle)" },
          { q: "17. Correct the error: 'Ils sont venu hier.'", answer: "Correction: 'Ils sont VENUS hier.' (plural -s required)" },
          { q: "18. Correct the error: 'Nous avons partis en vacances.'", answer: "Correction: 'Nous SOMMES partis en vacances.' (partir requires être)" },
          { q: "19. Form agreement: On est (arriver) ___ en retard (spoken by a mixed couple).", answer: "arrivés (on agreeing as informal nous in mixed plural)" },
          { q: "20. Form agreement: La reine est (mort) ___ en 1901.", answer: "morte" }
        ]
      },
      {
        id: "a2-passe-compose-etre-s3",
        sheetNum: 3,
        title: "Sheet 3: Dual-Auxiliary Verbs (Monter, Descendre, Sortir...)",
        subtitle: "20 Questions · Verbs taking Être when intransitive and Avoir when taking a direct object",
        exercises: [
          { q: "1. Which 6 movement verbs can take either Avoir or Être depending on transitivity?", answer: "monter, descendre, sortir, rentrer, retourner, passer" },
          { q: "2. Rule: When these verbs take a DIRECT OBJECT, which auxiliary do they take?", answer: "AVOIR (and the participle does NOT agree with the subject)." },
          { q: "3. Choose auxiliary: Je (suis / ai) monté au dernier étage (no object).", answer: "suis monté (movement of subject → être)" },
          { q: "4. Choose auxiliary: J' (suis / ai) monté les valises dans la chambre (with object 'les valises').", answer: "ai monté (transitive with direct object → avoir)" },
          { q: "5. Choose auxiliary: Elle (est / a) sortie avec ses amis (no object).", answer: "est sortie (intransitive → être)" },
          { q: "6. Choose auxiliary: Elle (est / a) sorti son passeport de son sac (with object 'son passeport').", answer: "a sorti (transitive → avoir)" },
          { q: "7. Choose auxiliary: Nous (sommes / avons) descendus par l'ascenseur.", answer: "sommes descendus (intransitive → être)" },
          { q: "8. Choose auxiliary: Nous (sommes / avons) descendu les cartons à la cave.", answer: "avons descendu (transitive → avoir)" },
          { q: "9. Choose auxiliary: Il (est / a) retourné en France pour les vacances.", answer: "est retourné (intransitive: returned to → être)" },
          { q: "10. Choose auxiliary: Il (est / a) retourné la crêpe dans la poêle.", answer: "a retourné (transitive: flipped over → avoir)" },
          { q: "11. Choose auxiliary: Je (suis / ai) passé par Lyon.", answer: "suis passé (passed through → être)" },
          { q: "12. Choose auxiliary: J' (suis / ai) passé un examen important.", answer: "ai passé (took/passed an exam → avoir)" },
          { q: "13. Translate: 'She went down to reception.'", answer: "Elle est descendue à la réception." },
          { q: "14. Translate: 'She brought down the luggage.'", answer: "Elle a descendu les bagages." },
          { q: "15. Translate: 'They went out at 8:00 PM.' (m. pl.)", answer: "Ils sont sortis à vingt heures." },
          { q: "16. Translate: 'He took out his wallet to pay.'", answer: "Il a sorti son portefeuille pour payer." },
          { q: "17. Translate: 'We spent a wonderful weekend in Nice.'", answer: "Nous avons passé un week-end magnifique à Nice." },
          { q: "18. Translate: 'The letter carrier stopped by this morning.' (passer)", answer: "Le facteur est passé ce matin." },
          { q: "19. Make negative: 'Elle n'est pas sortie ce soir.'", answer: "Elle n'est pas sortie ce soir." },
          { q: "20. Make negative: 'Il n'a pas sorti la poubelle.'", answer: "Il n'a pas sorti la poubelle." }
        ]
      }
    ],

    "a2-imparfait": [
      {
        id: "a2-imparfait-s1",
        sheetNum: 1,
        title: "Sheet 1: Formation from the 'Nous' Stem & Invariable Endings",
        subtitle: "20 Questions · Deriving stems and applying -ais, -ais, -ait, -ions, -iez, -aient",
        exercises: [
          { q: "1. What is the formula for finding the stem of the Imparfait for any verb?", answer: "Take the present tense 'nous' form and remove '-ons' (e.g. nous parlons → parl-)." },
          { q: "2. What are the six endings of the Imparfait for all French verbs without exception?", answer: "-ais, -ais, -ait, -ions, -iez, -aient" },
          { q: "3. What is the ONLY irregular stem in the entire Imparfait tense in French?", answer: "ÊTRE (stem: ét- → j'étais, tu étais... derived from Latin, since nous sommes has no -ons)" },
          { q: "4. Form the Imparfait: Je (parler)", answer: "Je parlais" },
          { q: "5. Form the Imparfait: Tu (parler)", answer: "Tu parlais" },
          { q: "6. Form the Imparfait: Il / Elle / On (parler)", answer: "Il parlait" },
          { q: "7. Form the Imparfait: Nous (parler)", answer: "Nous parlions" },
          { q: "8. Form the Imparfait: Vous (parler)", answer: "Vous parliez" },
          { q: "9. Form the Imparfait: Ils / Elles (parler)", answer: "Ils parlaient" },
          { q: "10. In pronunciation, how many of the forms of 'parler' sound identical [par-lay]?", answer: "Four forms: je parlais, tu parlais, il parlait, ils parlaient." },
          { q: "11. Find the stem and conjugate: 'finir' (nous finissons) with 'Nous'.", answer: "Nous finissions (stem: finiss-)" },
          { q: "12. Find the stem and conjugate: 'faire' (nous faisons) with 'Je'.", answer: "Je faisais [fe-zay]" },
          { q: "13. Find the stem and conjugate: 'prendre' (nous prenons) with 'Ils'.", answer: "Ils prenaient" },
          { q: "14. Find the stem and conjugate: 'avoir' (nous avons) with 'Elle'.", answer: "Elle avait" },
          { q: "15. Conjugate 'être' with 'Tu'.", answer: "Tu étais" },
          { q: "16. Conjugate 'être' with 'Nous'.", answer: "Nous étions" },
          { q: "17. Conjugate 'manger' with 'Je' (preserve soft g).", answer: "Je mangeais (note the 'e' before -ais)" },
          { q: "18. Conjugate 'manger' with 'Nous' (does it need an extra 'e' before -ions?).", answer: "Nous mangions (NO extra 'e', since 'i' already keeps g soft)" },
          { q: "19. Conjugate 'commencer' with 'Il' (cédille needed?).", answer: "Il commençait (ç before a)" },
          { q: "20. Conjugate 'commencer' with 'Vous'.", answer: "Vous commenciez (no cédille before i)" }
        ]
      },
      {
        id: "a2-imparfait-s2",
        sheetNum: 2,
        title: "Sheet 2: Values of the Imparfait: Habit, Description & Ongoing States",
        subtitle: "20 Questions · Identifying descriptive background, weather, emotions and past habits",
        exercises: [
          { q: "1. Which tense expresses repeated habitual actions in the past ('used to do / would do')?", answer: "L'Imparfait" },
          { q: "2. Which tense sets the physical or psychological background scene in a narrative?", answer: "L'Imparfait (weather, hour, physical descriptions, mental states)" },
          { q: "3. Translate: 'When I was young, I lived in Marseille.'", answer: "Quand j'étais jeune, j'habitais à Marseille." },
          { q: "4. Translate: 'Every summer, we went to the beach.' (habitual)", answer: "Chaque été, nous allions à la plage." },
          { q: "5. Translate: 'It was cold and it was raining.' (weather background)", answer: "Il faisait froid et il pleuvait." },
          { q: "6. Translate: 'The house had three large windows.' (description)", answer: "La maison avait trois grandes fenêtres." },
          { q: "7. Translate: 'He was tired and he was hungry.' (state)", answer: "Il était fatigué et il avait faim." },
          { q: "8. Translate: 'It was 10:00 PM.' (hour)", answer: "Il était vingt-deux heures (or dix heures du soir)." },
          { q: "9. Translate: 'She was wearing a black dress.'", answer: "Elle portait une robe noire." },
          { q: "10. Translate: 'We wanted to travel.'", answer: "Nous voulions voyager." },
          { q: "11. Translate: 'Did you know that?' (informal, ongoing knowledge)", answer: "Tu savais ça ?" },
          { q: "12. Translate: 'I was thinking about my family.'", answer: "Je pensais à ma famille." },
          { q: "13. Translate: 'The streets were quiet on Sundays.'", answer: "Les rues étaient calmes le dimanche." },
          { q: "14. Complete with Imparfait: Autrefois, les gens (écrire) ___ des lettres.", answer: "écrivaient" },
          { q: "15. Complete: À cette époque, nous ne (connaître) ___ pas Internet.", answer: "connaissions" },
          { q: "16. Complete: Mon grand-père (lire) ___ le journal tous les matins.", answer: "lisait" },
          { q: "17. What polite suggestion formula begins with 'Si on...' + Imparfait?", answer: "'Si on allait au cinéma ?' (How about going to the movies?)" },
          { q: "18. Translate: 'How about having a coffee?' (suggestion using Si on...)", answer: "Si on prenait un café ?" },
          { q: "19. Translate: 'She had blonde hair and blue eyes.'", answer: "Elle avait les cheveux blonds et les yeux bleus." },
          { q: "20. Translate: 'I loved reading books by the fire.'", answer: "J'aimais lire des livres près du feu." }
        ]
      },
      {
        id: "a2-imparfait-s3",
        sheetNum: 3,
        title: "Sheet 3: The Interplay: Imparfait vs. Passé Composé",
        subtitle: "20 Questions · Choosing between ongoing background backdrop and interrupting plot events",
        exercises: [
          { q: "1. Rule of thumb: If an action interrupts an ongoing backdrop, which tense is the background and which is the interruption?", answer: "Background = Imparfait; Interruption = Passé Composé." },
          { q: "2. Choose tenses: Je (dormir) quand le téléphone (sonner).", answer: "Je dormais (imp.) quand le téléphone a sonné (PC)." },
          { q: "3. Choose tenses: Pendant que nous (déjeuner), Sophie (arriver).", answer: "Pendant que nous déjeunions (imp.), Sophie est arrivée (PC)." },
          { q: "4. Choose tenses: Il (faire) beau, alors nous (décider) de sortir.", answer: "Il faisait beau (imp.), alors nous avons décidé de sortir (PC)." },
          { q: "5. Choose tenses: Quand j' (être) à Paris, j' (visiter) le Louvre trois fois.", answer: "Quand j'étais à Paris (imp.), j'ai visité le Louvre trois fois (PC — specific number of completed times)." },
          { q: "6. Choose tenses: Soudain, un orage (éclater).", answer: "Soudain, un orage a éclaté (PC — sudden punctual event)." },
          { q: "7. Does a time limit indicator like 'pendant deux heures hier' trigger PC or Imparfait?", answer: "Passé Composé (marks a bounded, completed block of time: 'J'ai attendu pendant deux heures')." },
          { q: "8. Choose: Hier matin, je (me réveiller) à 7h.", answer: "me suis réveillé(e) (PC — completed point in time)" },
          { q: "9. Choose: Tous les matins, je (se réveiller) à 7h.", answer: "me réveillais (Imparfait — repeating habit)" },
          { q: "10. Translate: 'I was driving when a deer crossed the road.'", answer: "Je conduisais quand un cerf a traversé la route." },
          { q: "11. Translate: 'She was working when the power went out.'", answer: "Elle travaillait quand l'électricité a coupé." },
          { q: "12. Translate: 'He was 20 when he left his country.'", answer: "Il avait vingt ans quand il a quitté son pays." },
          { q: "13. Translate: 'We were reading quietly, then someone knocked on the door.'", answer: "Nous lisions tranquillement, puis quelqu'un a frappé à la porte." },
          { q: "14. Correct the error: 'Hier, il faisait beau et soudain il pleuvait.'", answer: "Correction: '...soudain il a plu.' (sudden event requires PC)" },
          { q: "15. Correct the error: 'Quand j'ai été petit, j'ai aimé les bonbons.'", answer: "Correction: 'Quand j'étais petit, j'aimais les bonbons.' (ongoing childhood state/habit requires Imparfait)" },
          { q: "16. Choose: L'année dernière, nous (voyager) au Japon.", answer: "avons voyagé (PC — completed trip)" },
          { q: "17. Choose: À cette époque, nous (voyager) souvent.", answer: "voyagions (Imparfait — frequency marker 'souvent')" },
          { q: "18. Translate: 'What were you doing when I called?'", answer: "Qu'est-ce que tu faisais quand j'ai appelé ?" },
          { q: "19. Translate: 'I was watching a film.'", answer: "Je regardais un film." },
          { q: "20. Summarize the narrative dichotomy between PC and Imparfait in one sentence.", answer: "L'Imparfait paints the continuous backdrop scenery (who, what, feelings, setting), while the Passé Composé advances the plot with discrete sequential actions." }
        ]
      }
    ],

    "a2-object-pronoun-order": [
      {
        id: "a2-object-pronoun-order-s1",
        sheetNum: 1,
        title: "Sheet 1: Direct Object Pronouns (le, la, les) in Isolation",
        subtitle: "20 Questions · Replacing direct nouns and positioning pronouns before conjugated verbs",
        exercises: [
          { q: "1. What are the third-person direct object pronouns (COD)?", answer: "le (m. sing.), la (f. sing.), l' (before vowel), les (pl.)" },
          { q: "2. Replace with COD: 'Je regarde le film.'", answer: "Je le regarde." },
          { q: "3. Replace with COD: 'Elle écoute la radio.'", answer: "Elle l'écoute." },
          { q: "4. Replace with COD: 'Nous attendons le train.'", answer: "Nous l'attendons." },
          { q: "5. Replace with COD: 'Ils préparent les dossiers.'", answer: "Ils les préparent." },
          { q: "6. Replace with COD: 'Tu connais cette femme ?'", answer: "Tu la connais ?" },
          { q: "7. Replace with COD: 'J'aime le café.'", answer: "Je l'aime." },
          { q: "8. Make negative: 'Je le regarde.'", answer: "Je ne le regarde pas." },
          { q: "9. Make negative: 'Elle l'écoute.'", answer: "Elle ne l'écoute pas." },
          { q: "10. Make negative: 'Nous les attendons.'", answer: "Nous ne les attendons pas." },
          { q: "11. Where does the pronoun go when there is a semi-auxiliary + infinitive (e.g. vouloir regarder)?", answer: "Directly in front of the INFINITIVE: 'Je veux le regarder'." },
          { q: "12. Replace with COD: 'Je veux lire ce livre.'", answer: "Je veux le lire." },
          { q: "13. Replace with COD: 'Nous allons signer le contrat.'", answer: "Nous allons le signer." },
          { q: "14. Replace with COD: 'Elle doit finir les rapports.'", answer: "Elle doit les finir." },
          { q: "15. Replace with COD: 'Tu peux m'aider ?'", answer: "('me' is already a pronoun; object pronoun precedes infinitive 'aider')" },
          { q: "16. In Passé Composé, where does the COD pronoun go?", answer: "Before the auxiliary verb: 'Je l'ai vu'." },
          { q: "17. Replace with COD: 'J'ai vu Pierre hier.'", answer: "Je l'ai vu hier." },
          { q: "18. Replace with COD in Passé Composé with agreement: 'J'ai acheté la maison.'", answer: "Je l'ai achetée. (participle agrees with preceding COD 'la')" },
          { q: "19. Replace with COD with agreement: 'Il a pris les clés.'", answer: "Il les a prises." },
          { q: "20. Replace with COD with agreement: 'Nous avons invité nos amies.'", answer: "Nous les avons invitées." }
        ]
      },
      {
        id: "a2-object-pronoun-order-s2",
        sheetNum: 2,
        title: "Sheet 2: Indirect Object Pronouns (lui, leur) vs. COD",
        subtitle: "20 Questions · Verbs governing the preposition à (parler à, téléphoner à, donner à)",
        exercises: [
          { q: "1. What are the two third-person indirect object pronouns (COI)?", answer: "lui (to him / to her — singular invariable for gender) and leur (to them — plural)" },
          { q: "2. Is 'lui' used for both men and women in indirect objects?", answer: "YES. 'Lui' means 'to him' OR 'to her' (e.g. 'Je lui parle' = I speak to him/her)." },
          { q: "3. Does 'leur' (indirect pronoun) ever take an -s?", answer: "NO. The pronoun 'leur' is strictly invariable (never 'leurs' as a pronoun!)." },
          { q: "4. Replace the indirect object: 'Je parle à Marc.'", answer: "Je lui parle." },
          { q: "5. Replace the indirect object: 'Je parle à Sophie.'", answer: "Je lui parle." },
          { q: "6. Replace the indirect object: 'Nous écrivons à nos clients.'", answer: "Nous leur écrivons." },
          { q: "7. Replace the indirect object: 'Elle téléphone à ses parents.'", answer: "Elle leur téléphone." },
          { q: "8. Replace with COI: 'Tu as répondu au directeur ?'", answer: "Tu lui as répondu ?" },
          { q: "9. Replace with COI: 'Il donne les clés à sa collègue.'", answer: "Il lui donne les clés." },
          { q: "10. Replace with COI: 'Nous offrons un cadeau aux enfants.'", answer: "Nous leur offrons un cadeau." },
          { q: "11. Does the past participle agree with a preceding COI (lui, leur)?", answer: "NO. Participles only agree with preceding direct objects (COD), NEVER with indirect objects." },
          { q: "12. Form participle: 'Je leur ai (parlé / parlés).' Choose correct.", answer: "parlé (no agreement with COI 'leur')" },
          { q: "13. Form participle: 'Il lui a (écrit / écrite) une lettre.' Choose correct.", answer: "écrit (no agreement with COI 'lui')" },
          { q: "14. Make negative: 'Je lui réponds.'", answer: "Je ne lui réponds pas." },
          { q: "15. Make negative: 'Elle leur a téléphoné.'", answer: "Elle ne leur a pas téléphoné." },
          { q: "16. Distinguish: Does 'écouter' take COD or COI?", answer: "COD (écouter quelqu'un → Je l'écoute, not Je lui écoute)." },
          { q: "17. Distinguish: Does 'téléphoner' take COD or COI?", answer: "COI (téléphoner À quelqu'un → Je lui téléphone)." },
          { q: "18. Distinguish: Does 'attendre' take COD or COI?", answer: "COD (attendre quelqu'un → Je l'attends)." },
          { q: "19. Distinguish: Does 'demander' take COD or COI for the person asked?", answer: "COI (demander À quelqu'un → Je lui demande)." },
          { q: "20. Distinguish: Does 'aider' take COD or COI?", answer: "COD (aider quelqu'un → Je l'aide, not Je lui aide)." }
        ]
      },
      {
        id: "a2-object-pronoun-order-s3",
        sheetNum: 3,
        title: "Sheet 3: Dual Pronoun Stacking Order & Imperative Shifts",
        subtitle: "20 Questions · Applying the pronoun sequence matrix and affirmative imperative hyphens",
        exercises: [
          { q: "1. What is the standard declarative pronoun order before the verb?", answer: "[me/te/se/nous/vous] before [le/la/les] before [lui/leur] before [y] before [en]." },
          { q: "2. Replace both objects: 'Il me donne le livre.'", answer: "Il me le donne." },
          { q: "3. Replace both objects: 'Je te prête ma voiture.'", answer: "Je te la prête." },
          { q: "4. Replace both objects: 'Elle donne le dossier à son chef.'", answer: "Elle le lui donne. (le before lui)" },
          { q: "5. Replace both objects: 'Nous expliquons la situation aux clients.'", answer: "Nous la leur expliquons. (la before leur)" },
          { q: "6. Replace both objects: 'Il a envoyé les documents à Sophie.'", answer: "Il les lui a envoyés. (agreement with COD 'les')" },
          { q: "7. Make negative: 'Il me le donne.'", answer: "Il ne me le donne pas." },
          { q: "8. Make negative: 'Elle le lui explique.'", answer: "Elle ne le lui explique pas." },
          { q: "9. Where do pronouns go in the AFFIRMATIVE imperative (e.g. 'Give it to me!')?", answer: "After the verb with hyphens: 'Donne-le-moi !' ('me' becomes 'moi')." },
          { q: "10. Form the affirmative imperative: 'Donne (le livre) à moi.'", answer: "Donne-le-moi !" },
          { q: "11. Form the affirmative imperative: 'Montrez (les photos) à nous.'", answer: "Montrez-les-nous !" },
          { q: "12. Form the affirmative imperative: 'Envoyez (le contrat) à lui.'", answer: "Envoyez-le-lui !" },
          { q: "13. Where do pronouns go in the NEGATIVE imperative ('Don't give it to him!')?", answer: "Before the verb (standard order): 'Ne le lui donne pas !'" },
          { q: "14. Form the negative imperative: 'Ne donne pas (le livre) à lui.'", answer: "Ne le lui donne pas !" },
          { q: "15. Form the negative imperative: 'Ne dis pas (cela) à eux.'", answer: "Ne le leur dis pas !" },
          { q: "16. Correct the error: 'Je lui le donnerai demain.'", answer: "Correction: 'Je LE LUI donnerai demain.' (le precedes lui)" },
          { q: "17. Correct the error: 'Donne-moi-le !'", answer: "Correction: 'Donne-le-moi !' (in affirmative imperative, COD precedes COI)" },
          { q: "18. Translate: 'Can you lend it to me?' (informal)", answer: "Tu peux me le prêter ?" },
          { q: "19. Translate: 'I am going to explain it to them.'", answer: "Je vais le leur expliquer." },
          { q: "20. Translate: 'She showed them to us.'", answer: "Elle nous les a montrés (or montrées)." }
        ]
      }
    ]
  };

  root.GRAMMAR_A2_WORKSHEETS = grammarA2Worksheets;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = grammarA2Worksheets;
  }
})(typeof window !== "undefined" ? window : globalThis);
