(function (root) {
  const skillsA1Worksheets = {
    "a1-reading-dialogue": [
      {
        id: "a1-reading-dialogue-s1",
        sheetNum: 1,
        title: "Sheet 1: Authentic Café & Bistro Vocabulary & Formulae",
        subtitle: "20 Questions · Essential terminology for French menus, dining and orders",
        exercises: [
          { q: "1. What does 'Le plat du jour' mean on a French bistro slate?", answer: "The daily special (dish of the day)" },
          { q: "2. What is the difference between 'Une formule' and 'À la carte'?", answer: "'Une formule' is a fixed-price set menu (e.g. entrée + plat); 'À la carte' means ordering individual items separately." },
          { q: "3. What does 'Une carafe d'eau' mean, and is it free in France by law?", answer: "A pitcher of tap water; yes, restaurants in France are legally required to provide free tap water to diners." },
          { q: "4. What does 'Service compris' mean on a French restaurant bill?", answer: "Tip / service charge is already included in the price (typically 15% built-in by French law)." },
          { q: "5. What is 'L'addition'?", answer: "The bill / check" },
          { q: "6. Translate: 'Un café noir, s'il vous plaît.'", answer: "A black coffee (espresso), please." },
          { q: "7. In a French café, what do you order if you want coffee with steamed milk?", answer: "Un café au lait (or un crème / café crème)." },
          { q: "8. What is 'Une noisette' in a French café?", answer: "An espresso with just a small drop (dash) of warm milk." },
          { q: "9. What is 'De l'eau gazeuse'?", answer: "Sparkling / carbonated water" },
          { q: "10. What is 'De l'eau plate'?", answer: "Still / non-carbonated water" },
          { q: "11. What is 'Une entrée' in a French meal sequence?", answer: "The appetizer / starter (unlike American English where entrée often means main dish!)." },
          { q: "12. What is 'Le plat principal'?", answer: "The main course" },
          { q: "13. What is 'Une boisson comprise'?", answer: "A drink included in the set menu" },
          { q: "14. How is meat cooked 'saignant'?", answer: "Rare" },
          { q: "15. How is meat cooked 'à point'?", answer: "Medium (pink center)" },
          { q: "16. How is meat cooked 'bien cuit'?", answer: "Well-done" },
          { q: "17. What is 'Un pourboire'?", answer: "A voluntary tip left for exceptional service" },
          { q: "18. Translate: 'Avez-vous une table pour deux personnes ?'", answer: "Do you have a table for two people?" },
          { q: "19. Translate: 'Je vais prendre le menu à 18 euros.'", answer: "I will take the 18-euro set menu." },
          { q: "20. Translate: 'C'était délicieux, merci.'", answer: "It was delicious, thank you." }
        ]
      },
      {
        id: "a1-reading-dialogue-s2",
        sheetNum: 2,
        title: "Sheet 2: Menu Decoding, Prices & Dietary Restrictions",
        subtitle: "20 Questions · Deciphering French bills, allergies and special requests",
        exercises: [
          { q: "1. A menu reads: 'Formule Midi : Entrée + Plat OU Plat + Dessert à 16,50 €'. How many courses do you get?", answer: "Two courses (either starter + main, or main + dessert)." },
          { q: "2. How do you inform a waiter that you are vegetarian in French?", answer: "Je suis végétarien (m.) / Je suis végétarienne (f.)." },
          { q: "3. How do you say 'I am allergic to gluten' in French?", answer: "Je suis allergique au gluten." },
          { q: "4. How do you say 'I am allergic to peanuts / nuts'?", answer: "Je suis allergique aux arachides / aux fruits à coque." },
          { q: "5. What does 'Fait maison' mean on a French menu?", answer: "Homemade / prepared on-site from fresh, raw ingredients (a protected French legal label)." },
          { q: "6. A receipt lists: '1x Croque-Monsieur 9,50 €, 1x Salade verte 3,50 €, 1x Pression 4,00 €'. What is the total?", answer: "17,00 € (dix-sept euros)" },
          { q: "7. What is 'Une bière pression'?", answer: "A draft / tap beer" },
          { q: "8. Translate: 'Sans oignons, s'il vous plaît.'", answer: "Without onions, please." },
          { q: "9. Translate: 'Est-ce qu'il y a du porc dans ce plat ?'", answer: "Is there any pork in this dish?" },
          { q: "10. What does 'Brut' mean when ordering cider or champagne?", answer: "Dry (low sugar), as opposed to 'Doux' (sweet)." },
          { q: "11. Translate: 'Pouvez-vous nous apporter du pain ?'", answer: "Can you bring us some bread?" },
          { q: "12. Translate: 'Acceptez-vous la carte bancaire ?'", answer: "Do you accept credit/debit cards?" },
          { q: "13. What is 'L'agneau' on a menu?", answer: "Lamb" },
          { q: "14. What is 'Le bœuf' on a menu?", answer: "Beef" },
          { q: "15. What is 'Le saumon' on a menu?", answer: "Salmon" },
          { q: "16. What is 'Les crevettes' on a menu?", answer: "Shrimp / prawns" },
          { q: "17. What is 'Une salade composée'?", answer: "A mixed salad with vegetables, proteins, and dressing" },
          { q: "18. Translate: 'Nous voulons payer séparément.'", answer: "We want to pay separately." },
          { q: "19. Translate: 'Gardez la monnaie.'", answer: "Keep the change." },
          { q: "20. How do you ask where the restrooms are in a restaurant?", answer: "Où sont les toilettes, s'il vous plaît ?" }
        ]
      },
      {
        id: "a1-reading-dialogue-s3",
        sheetNum: 3,
        title: "Sheet 3: Dialogue Comprehension & Cultural Café Etiquette",
        subtitle: "20 Questions · Full conversational comprehension and French dining culture",
        exercises: [
          { q: "1. In France, do servers bring the bill automatically when you finish eating?", answer: "No. Diners are encouraged to relax; you must ask for the bill: 'L'addition, s'il vous plaît.'" },
          { q: "2. What does 'En terrasse' mean when choosing a seat?", answer: "Outside on the patio / sidewalk seating (often priced slightly higher in historic Parisian cafés)." },
          { q: "3. What does 'Au comptoir' mean?", answer: "At the bar counter (traditionally cheaper for coffee than table service)." },
          { q: "4. Read the dialogue line: 'Serveur : Vous avez choisi ? Client : Oui, pour moi ce sera le pavé de saumon.' What did the customer order?", answer: "The salmon steak." },
          { q: "5. Read the line: 'Serveur : Et comme boisson ? Client : Une carafe d'eau et un verre de vin rouge.' What beverages were ordered?", answer: "A pitcher of tap water and a glass of red wine." },
          { q: "6. What does the server mean by 'Vous désirez un café pour terminer ?'", answer: "'Would you like a coffee to finish your meal?' (standard French post-dessert routine)." },
          { q: "7. Translate: 'Is everything going well?' (standard waiter check-in)", answer: "Tout se passe bien ? (or 'Ça a été ?' after finishing)." },
          { q: "8. How do you reply that everything is very good?", answer: "Oui, c'est très bon, merci !" },
          { q: "9. Translate: 'I didn't order this.'", answer: "Je n'ai pas commandé cela (or 'Ce n'est pas ce que j'ai commandé')." },
          { q: "10. What does 'Le couvert' mean in French dining?", answer: "The place setting (cutlery, plate, glass, napkin)." },
          { q: "11. Translate: 'Could we have another fork, please?'", answer: "Pourrions-nous avoir une autre fourchette, s'il vous plaît ?" },
          { q: "12. What is 'Une formule petit-déjeuner' typically comprised of?", answer: "A hot drink (coffee/tea), a croissant or tartine with butter/jam, and orange juice." },
          { q: "13. Translate: 'Are you open on Sundays?'", answer: "Êtes-vous ouvert le dimanche ?" },
          { q: "14. Translate: 'Is booking recommended?'", answer: "La réservation est-elle recommandée ?" },
          { q: "15. What does 'Complet' mean on a restaurant door sign?", answer: "Full / no tables available" },
          { q: "16. In France, is it customary to ask for a doggy bag for unfinished meals?", answer: "Historically rare, but now legally permitted and increasingly accepted ('un emporte-reste' / doggy bag)." },
          { q: "17. Translate: 'We had a lovely evening.'", answer: "Nous avons passé une excellente soirée." },
          { q: "18. Translate: 'Excuse me, the bill contains an error.'", answer: "Excusez-moi, l'addition contient une erreur." },
          { q: "19. Translate: 'Do you take American Express?'", answer: "Prenez-vous l'American Express ?" },
          { q: "20. What is the traditional toast when clinking glasses?", answer: "Santé ! (looking the person directly in the eye, per French social custom)." }
        ]
      }
    ],

    "a1-writing-sentences": [
      {
        id: "a1-writing-sentences-s1",
        sheetNum: 1,
        title: "Sheet 1: Subject-Verb-Object Word Order & Punctuation",
        subtitle: "20 Questions · Constructing standard French declarative sentences with correct spacing",
        exercises: [
          { q: "1. What is the standard declarative word order in a basic French sentence?", answer: "SVO: Subject + Verb + Object (e.g. Marie aime le café)." },
          { q: "2. In French typography, do two-part punctuation marks (: ; ? !) require a space before them?", answer: "YES. Standard French requires a non-breaking space before colons, semicolons, question marks, and exclamation marks." },
          { q: "3. Reorder into a grammatically correct sentence: 'à Paris / habite / Pierre / avec sa femme'.", answer: "Pierre habite à Paris avec sa femme." },
          { q: "4. Reorder: 'tous les matins / un café noir / bois / je'.", answer: "Je bois un café noir tous les matins." },
          { q: "5. Reorder: 'les nouveaux projets / étudient / les ingénieurs'.", answer: "Les ingénieurs étudient les nouveaux projets." },
          { q: "6. Reorder: 'à 18 heures / ferme / le bureau'.", answer: "Le bureau ferme à 18 heures." },
          { q: "7. Reorder: 'au directeur / une lettre / écrit / Sophie'.", answer: "Sophie écrit une lettre au directeur." },
          { q: "8. Add proper French punctuation and spacing: 'Comment vous appelez vous'", answer: "Comment vous appelez-vous ?" },
          { q: "9. Add proper French punctuation: 'Bonjour merci beaucoup'", answer: "Bonjour, merci beaucoup !" },
          { q: "10. In French, are months and days of the week capitalized (e.g. lundi, juillet)?", answer: "NO. Days and months are lowercase in French unless starting a sentence (lundi, mardi, janvier, février)." },
          { q: "11. Are language names capitalized in French when used as nouns (le français)?", answer: "NO. Languages are lowercase: 'J'apprends le français' (only nationalities as proper nouns are capitalized: 'Les Français')." },
          { q: "12. Write a complete sentence: Subject = 'Nous', Verb = 'aimer', Object = 'la cuisine française'.", answer: "Nous aimons la cuisine française." },
          { q: "13. Write a complete sentence: Subject = 'Mon frère', Verb = 'travailler', Place = 'dans une banque'.", answer: "Mon frère travaille dans une banque." },
          { q: "14. Write a complete sentence: Subject = 'Vous', Verb = 'parler', Object = 'trois langues'.", answer: "Vous parlez trois langues." },
          { q: "15. Translate: 'I live in an apartment.'", answer: "J'habite dans un appartement." },
          { q: "16. Translate: 'She reads the newspaper every day.'", answer: "Elle lit le journal tous les jours." },
          { q: "17. Translate: 'The train arrives at 14:30.'", answer: "Le train arrive à quatorze heures trente (14h30)." },
          { q: "18. Translate: 'We are preparing the meeting.'", answer: "Nous préparons la réunion." },
          { q: "19. Translate: 'My colleagues are very competent.'", answer: "Mes collègues sont très compétents." },
          { q: "20. Correct the syntax error: 'Parle français très bien il.'", answer: "Correction: 'Il parle très bien français.'" }
        ]
      },
      {
        id: "a1-writing-sentences-s2",
        sheetNum: 2,
        title: "Sheet 2: Affirmative to Negative Sentence Transformations",
        subtitle: "20 Questions · Mastering ne... pas, ne... plus, ne... jamais with full sentence re-writing",
        exercises: [
          { q: "1. Transform to negative (ne... pas): 'J'aime le thé.'", answer: "Je n'aime pas le thé." },
          { q: "2. Transform: 'Il travaille le samedi.'", answer: "Il ne travaille pas le samedi." },
          { q: "3. Transform: 'Nous habitons à Lyon.'", answer: "Nous n'habitons pas à Lyon." },
          { q: "4. Transform: 'Elle comprend l'exercice.'", answer: "Elle ne comprend pas l'exercice." },
          { q: "5. Transform: 'Vous avez des questions.' (Observe article shift)", answer: "Vous n'avez pas de questions. (des becomes de)" },
          { q: "6. Transform: 'Je prends du sucre.'", answer: "Je ne prends pas de sucre. (du becomes de)" },
          { q: "7. Transform: 'Il y a une erreur dans le document.'", answer: "Il n'y a pas d'erreur dans le document." },
          { q: "8. Transform: 'C'est un problème grave.' (Warning: verb is être)", answer: "Ce n'est pas un problème grave. (un remains un with être)" },
          { q: "9. Transform to 'ne... plus' (no longer): 'Il habite encore à Paris.'", answer: "Il n'habite plus à Paris." },
          { q: "10. Transform to 'ne... plus': 'Je fume.'", answer: "Je ne fume plus." },
          { q: "11. Transform to 'ne... jamais' (never): 'Elle prend le métro.'", answer: "Elle ne prend jamais le métro." },
          { q: "12. Transform to 'ne... jamais': 'Je mange de la viande.'", answer: "Je ne mange jamais de viande." },
          { q: "13. Transform to 'ne... rien' (nothing): 'Je comprends tout.'", answer: "Je ne comprends rien." },
          { q: "14. Transform to 'ne... rien': 'Il a dit quelque chose.'", answer: "Il n'a rien dit." },
          { q: "15. Transform to 'ne... personne' (nobody): 'Je connais tout le monde.'", answer: "Je ne connais personne." },
          { q: "16. Transform: 'Nous allons regarder ce film ce soir.' (Futur proche negation)", answer: "Nous n'allons pas regarder ce film ce soir." },
          { q: "17. Transform: 'Il a fini son devoir hier.' (Passé composé negation)", answer: "Il n'a pas fini son devoir hier." },
          { q: "18. Translate: 'I never drink coffee in the evening.'", answer: "Je ne bois jamais de café le soir." },
          { q: "19. Translate: 'He no longer works here.'", answer: "Il ne travaille plus ici." },
          { q: "20. Translate: 'We don't have any cash.'", answer: "Nous n'avons pas d'argent liquide (or d'espèces)." }
        ]
      },
      {
        id: "a1-writing-sentences-s3",
        sheetNum: 3,
        title: "Sheet 3: Logical Connectors: Mais, Et, Parce Que, Donc",
        subtitle: "20 Questions · Linking clauses to express addition, contrast, cause and consequence",
        exercises: [
          { q: "1. What connector expresses addition ('and')?", answer: "Et" },
          { q: "2. What connector expresses contrast ('but')?", answer: "Mais" },
          { q: "3. What connector introduces a cause ('because')?", answer: "Parce que (or parce qu' before a vowel)" },
          { q: "4. What connector introduces a consequence ('so / therefore')?", answer: "Donc (or alors)" },
          { q: "5. Link with MAIS: 'J'aime le français. C'est une langue difficile.'", answer: "J'aime le français, mais c'est une langue difficile." },
          { q: "6. Link with ET: 'Il parle anglais. Il parle espagnol.'", answer: "Il parle anglais et espagnol." },
          { q: "7. Link with PARCE QUE: 'Je ne viens pas. Je suis malade.'", answer: "Je ne viens pas parce que je suis malade." },
          { q: "8. Link with PARCE QU': 'Elle est en retard. Elle a raté son train.'", answer: "Elle est en retard parce qu'elle a raté son train." },
          { q: "9. Link with DONC: 'Il pleut. Nous restons à la maison.'", answer: "Il pleut, donc nous restons à la maison." },
          { q: "10. Link with ALORS: 'Je n'ai pas de voiture. Je prends le bus.'", answer: "Je n'ai pas de voiture, alors je prends le bus." },
          { q: "11. Translate: 'I want to travel, but I don't have enough money.'", answer: "Je veux voyager, mais je n'ai pas assez d'argent." },
          { q: "12. Translate: 'He studies hard because he wants to pass his exam.'", answer: "Il étudie beaucoup parce qu'il veut réussir son examen." },
          { q: "13. Translate: 'The restaurant was full, so we went to a bistro.'", answer: "Le restaurant était complet, donc nous sommes allés dans un bistrot." },
          { q: "14. Translate: 'She is French and she lives in Brussels.'", answer: "Elle est française et elle habite à Bruxelles." },
          { q: "15. Translate: 'First, I have breakfast; then, I go to work.' (D'abord... ensuite...)", answer: "D'abord, je prends le petit-déjeuner ; ensuite, je vais au travail." },
          { q: "16. Fill in the connector: Je voudrais venir, ___ je dois travailler ce soir.", answer: "mais" },
          { q: "17. Fill in the connector: Le musée est fermé le mardi, ___ venez mercredi.", answer: "donc (or alors)" },
          { q: "18. Fill in: Il a acheté une chemise ___ une cravate.", answer: "et" },
          { q: "19. Fill in: Nous apprenons le français ___ nous aimons la culture.", answer: "parce que" },
          { q: "20. Write a 3-clause connected sentence using 'd'abord', 'puis', and 'enfin'.", answer: "D'abord je visite la ville, puis je déjeune au restaurant, et enfin je rentre à l'hôtel." }
        ]
      }
    ],

    "a1-speaking-introductions": [
      {
        id: "a1-speaking-introductions-s1",
        sheetNum: 1,
        title: "Sheet 1: Self-Presentation Elements (Name, Age, Profession, Origin)",
        subtitle: "20 Questions · Formulating fluent spoken personal profiles for DELF A1 speaking interviews",
        exercises: [
          { q: "1. State your name using 'Je m'appelle...'.", answer: "Je m'appelle [Votre Prénom et Nom]." },
          { q: "2. State your nationality (masculine and feminine forms, e.g. Canadian).", answer: "Je suis canadien (m.) / Je suis canadienne (f.)." },
          { q: "3. State your age: 'I am 35 years old.'", answer: "J'ai trente-cinq ans." },
          { q: "4. State your city of residence: 'I live in London.'", answer: "J'habite à Londres. (preposition 'à' before cities)" },
          { q: "5. State your country of origin: 'I come from the United States.'", answer: "Je viens des États-Unis. (or 'Je suis originaire des États-Unis')." },
          { q: "6. State your profession: 'I am a software engineer.' (Note: no article with profession)", answer: "Je suis ingénieur logiciel (never 'Je suis un ingénieur')." },
          { q: "7. State your marital status: 'I am married.'", answer: "Je suis marié (m.) / Je suis mariée (f.)." },
          { q: "8. State family details: 'I have two children, a boy and a girl.'", answer: "J'ai deux enfants, un garçon et une fille." },
          { q: "9. State language abilities: 'I speak English and a little French.'", answer: "Je parle anglais et un peu français." },
          { q: "10. State hobbies: 'In my free time, I like to run and read.'", answer: "Pendant mon temps libre, j'aime courir et lire." },
          { q: "11. Formulate the question to ask someone their name (formal).", answer: "Comment vous appelez-vous ?" },
          { q: "12. Formulate the question to ask someone their nationality (formal).", answer: "Quelle est votre nationalité ?" },
          { q: "13. Formulate the question to ask someone their profession (formal).", answer: "Quelle est votre profession ? (or 'Que faites-vous dans la vie ?')" },
          { q: "14. Formulate the question to ask someone where they live (formal).", answer: "Où habitez-vous ?" },
          { q: "15. Formulate the question to ask someone their age (formal).", answer: "Quel âge avez-vous ?" },
          { q: "16. Formulate: 'Nice to meet you, Mr. Dubois.'", answer: "Enchanté, Monsieur Dubois." },
          { q: "17. Translate: 'I have been studying French for six months.'", answer: "J'apprends le français depuis six mois." },
          { q: "18. Translate: 'My favorite sport is tennis.'", answer: "Mon sport préféré est le tennis." },
          { q: "19. Deliver a continuous 3-sentence self-presentation introduction.", answer: "Bonjour, je m'appelle David, j'ai 32 ans et je suis ingénieur à Toronto. J'habite actuellement à Paris pour mon travail et j'apprends le français." },
          { q: "20. What is the standard response when an examiner concludes the interview with 'Merci, c'est très bien'?", answer: "Merci à vous, bonne journée !" }
        ]
      },
      {
        id: "a1-speaking-introductions-s2",
        sheetNum: 2,
        title: "Sheet 2: Formulating Questions from Word Cues (DELF Part 2)",
        subtitle: "20 Questions · Building spontaneous questions using target stimulus words",
        exercises: [
          { q: "1. Word cue: HEURE. Form a question to ask the time.", answer: "Quelle heure est-il, s'il vous plaît ?" },
          { q: "2. Word cue: PRIX. Form a question to ask the cost of an item.", answer: "Quel est le prix de cet article ? (or 'Combien ça coûte ?')" },
          { q: "3. Word cue: TRAIN. Form a question about the next train to Lyon.", answer: "À quelle heure part le prochain train pour Lyon ?" },
          { q: "4. Word cue: RESTAURANT. Form a question asking for a recommendation.", answer: "Connaissez-vous un bon restaurant près d'ici ?" },
          { q: "5. Word cue: ENFANTS. Form a question asking if someone has children (formal).", answer: "Avez-vous des enfants ?" },
          { q: "6. Word cue: VACANCES. Form a question about holiday plans.", answer: "Où partez-vous en vacances cet été ?" },
          { q: "7. Word cue: WEEK-END. Form a question about weekend activities.", answer: "Qu'est-ce que vous faites ce week-end ?" },
          { q: "8. Word cue: MUSIQUE. Form a question about musical tastes.", answer: "Quel genre de musique aimez-vous ?" },
          { q: "9. Word cue: CAFÉ. Form a question inviting someone for coffee.", answer: "Voulez-vous prendre un café avec moi ?" },
          { q: "10. Word cue: LANGUES. Form a question about languages spoken.", answer: "Combien de langues parlez-vous ?" },
          { q: "11. Word cue: HÔTEL. Form a question about hotel vacancies.", answer: "Avez-vous une chambre libre pour ce soir ?" },
          { q: "12. Word cue: STATION. Form a question about the nearest subway station.", answer: "Où se trouve la station de métro la plus proche ?" },
          { q: "13. Word cue: JOUR. Form a question asking what day it is today.", answer: "Quel jour sommes-nous aujourd'hui ?" },
          { q: "14. Word cue: DATE. Form a question asking today's date.", answer: "Quelle est la date d'aujourd'hui ?" },
          { q: "15. Word cue: MÉTIER. Form a question asking about someone's career.", answer: "Quel est votre métier ?" },
          { q: "16. Word cue: PAIEMENT. Form a question about payment methods.", answer: "Est-ce que je peux payer par carte bancaire ?" },
          { q: "17. Word cue: OUVERTURE. Form a question about opening hours.", answer: "À quelle heure ouvre le magasin ?" },
          { q: "18. Word cue: FERMETURE. Form a question about closing hours.", answer: "À quelle heure fermez-vous ?" },
          { q: "19. Word cue: TOILETTES. Form a polite question.", answer: "Pardon, où sont les toilettes, s'il vous plaît ?" },
          { q: "20. Word cue: WIFI. Form a question asking for the password.", answer: "Quel est le mot de passe du wifi, s'il vous plaît ?" }
        ]
      },
      {
        id: "a1-speaking-introductions-s3",
        sheetNum: 3,
        title: "Sheet 3: Everyday Guided Role-Plays (DELF Part 3)",
        subtitle: "20 Questions · Simulated exchanges in a bakery, train station, and tourism office",
        exercises: [
          { q: "1. Scenario Baker: Greet the baker and ask for one traditional baguette and two croissants.", answer: "Bonjour madame, je voudrais une baguette tradition et deux croissants, s'il vous plaît." },
          { q: "2. The baker asks: 'Et avec ceci ?' What does this mean, and how do you reply 'That's all, thank you'?", answer: "It means 'And with that? / Anything else?'. Reply: 'Ce sera tout, merci !'" },
          { q: "3. Ask the baker how much it costs altogether.", answer: "Ça fait combien, s'il vous plaît ?" },
          { q: "4. You want to pay with a €20 note. What do you say when handing it over?", answer: "Voilà vingt euros." },
          { q: "5. Part politely from the shopkeeper after paying.", answer: "Merci beaucoup, bonne journée et au revoir !" },
          { q: "6. Scenario Ticket Counter: Ask for a round-trip ticket to Nice for tomorrow morning.", answer: "Bonjour monsieur, je voudrais un aller-retour pour Nice pour demain matin, s'il vous plaît." },
          { q: "7. The agent asks: 'En première ou en seconde classe ?'. Choose second class.", answer: "En seconde classe, s'il vous plaît." },
          { q: "8. Ask which platform the train departs from.", answer: "De quelle voie part le train ?" },
          { q: "9. Ask if you need to validate your ticket before boarding ('composter').", answer: "Est-ce qu'il faut composter le billet ?" },
          { q: "10. Scenario Tourism Office: Ask for a free map of the city.", answer: "Bonjour, avez-vous un plan de la ville, s'il vous plaît ?" },
          { q: "11. Ask what historic monuments can be visited on foot.", answer: "Quels monuments peut-on visiter à pied ?" },
          { q: "12. Ask if the museum is open on Mondays.", answer: "Le musée est-il ouvert le lundi ?" },
          { q: "13. Scenario Boutique: Ask if they have this shirt in size Medium.", answer: "Bonjour, avez-vous cette chemise en taille M, s'il vous plaît ?" },
          { q: "14. Ask where the fitting rooms are.", answer: "Où sont les cabines d'essayage, s'il vous plaît ?" },
          { q: "15. After trying it on, tell the sales clerk it is too small.", answer: "C'est un peu trop petit. Avez-vous la taille au-dessus ?" },
          { q: "16. Scenario Hotel: State that you have a reservation under the name Martin.", answer: "Bonjour, j'ai une réservation au nom de Martin." },
          { q: "17. Ask what time breakfast is served.", answer: "À quelle heure est servi le petit-déjeuner ?" },
          { q: "18. Ask if there is an elevator in the building.", answer: "Y a-t-il un ascenseur ?" },
          { q: "19. Ask for a taxi to be called for 6:00 AM tomorrow.", answer: "Pourriez-vous commander un taxi pour demain matin à six heures ?" },
          { q: "20. How do you conclude any everyday interaction politely in France?", answer: "Merci beaucoup pour votre aide, bonne journée, au revoir !" }
        ]
      }
    ],

    "a1-listening-comprehension": [
      {
        id: "a1-listening-comprehension-s1",
        sheetNum: 1,
        title: "Sheet 1: Auditory Number & Price Discrimination",
        subtitle: "20 Questions · Deciphering spoken amounts, gate numbers, and platform alerts",
        exercises: [
          { q: "1. Listen to the audio prompt: 'Votre addition est de quarante-sept euros cinquante.' Write the figure.", answer: "47,50 €" },
          { q: "2. Listen: 'Le train part de la voie dix-neuf.' Which platform number is this?", answer: "Platform 19 (voie 19)" },
          { q: "3. Listen: 'Rendez-vous à quatorze heures quarante-cinq.' What time is this in standard 12-hour format?", answer: "2:45 PM" },
          { q: "4. Listen: 'Le code de la porte est : soixante-douze, quatre-vingt-trois.' Write the keypad code.", answer: "7283" },
          { q: "5. Listen: 'Le vol AF 1380 embarque porte B 24.' What is the flight number and gate?", answer: "Flight AF1380, Gate B24" },
          { q: "6. Listen: 'Numéro de téléphone : 06 14 92 75 08.' Transcribe the 10 digits.", answer: "06 14 92 75 08" },
          { q: "7. Listen: 'Une réduction de trente pour cent sur tout le magasin.' What discount percentage is announced?", answer: "30%" },
          { q: "8. Listen: 'Le musée est fermé le premier mai et le vingt-cinq décembre.' Which two dates are mentioned?", answer: "May 1st and December 25th" },
          { q: "9. Listen: 'Il fait vingt-huit degrés à Marseille.' What is the temperature?", answer: "28 °C" },
          { q: "10. Listen: 'Votre commande numéro soixante-et-onze est prête.' Which order number is ready?", answer: "Order 71" },
          { q: "11. Listen: 'Le paquet pèse deux kilos trois cents grammes.' What is the weight?", answer: "2.3 kg (2 kg 300 g)" },
          { q: "12. Listen: 'Chambre quatre-vingt-seize au troisième étage.' What is the room number and floor?", answer: "Room 96, 3rd floor" },
          { q: "13. Listen: 'Billet aller simple : soixante-quinze euros.' What is the ticket price?", answer: "75 €" },
          { q: "14. Listen: 'Le cours commence à huit heures et demie précises.' What time does class start?", answer: "8:30 AM" },
          { q: "15. Listen: 'Vous avez rendez-vous le jeudi dix-sept mars.' What day and date are announced?", answer: "Thursday, March 17th" },
          { q: "16. Listen: 'TGV 6602 à destination de Lyon-Part-Dieu, départ 09h12.' Identify train number, destination, and departure time.", answer: "TGV 6602, to Lyon-Part-Dieu, departure 09:12" },
          { q: "17. Listen: 'Deux baguettes et trois éclairs : ça fait onze euros vingt.' What is the total cost?", answer: "11,20 €" },
          { q: "18. Listen: 'Composez le zéro un, quarante-deux, soixante-huit, dix-neuf, cinquante-quatre.' Transcribe the phone number.", answer: "01 42 68 19 54" },
          { q: "19. Listen: 'L'autobus numéro quatre-vingt-onze arrive dans trois minutes.' Which bus number is arriving?", answer: "Bus 91" },
          { q: "20. Listen: 'Le match commence dans un quart d'heure.' How many minutes until the match starts?", answer: "15 minutes" }
        ]
      },
      {
        id: "a1-listening-comprehension-s2",
        sheetNum: 2,
        title: "Sheet 2: Station & Airport Public Announcements",
        subtitle: "20 Questions · Interpreting track changes, delayed flights and emergency alerts",
        exercises: [
          { q: "1. An announcement states: 'Le TGV pour Bordeaux partira avec un retard de vingt minutes.' What is announced?", answer: "The high-speed train to Bordeaux is delayed by 20 minutes." },
          { q: "2. Announcement: 'Changement de voie : le train pour Lille partira voie C et non voie A.' Where should passengers go?", answer: "Platform C (voie C)." },
          { q: "3. Announcement: 'Attention à la fermeture automatique des portes, attention au départ.' What action is about to happen?", answer: "Doors are closing automatically; the train is about to depart." },
          { q: "4. Announcement: 'Dernier appel pour les passagers du vol Air France à destination de Rome.' What should passengers do?", answer: "Proceed immediately to boarding (final call for Rome)." },
          { q: "5. Announcement: 'Éloignez-vous de la bordure du quai, s'il vous plaît.' What safety warning is given?", answer: "Step back from the platform edge." },
          { q: "6. Announcement: 'Pour des raisons de sécurité, ne laissez pas vos bagages sans surveillance.' What is the instruction?", answer: "Do not leave luggage unattended for security reasons." },
          { q: "7. Announcement: 'Le train omnibus dessert toutes les gares jusqu'à Versailles.' What kind of train is this?", answer: "A local train stopping at every station up to Versailles." },
          { q: "8. Announcement: 'En raison de travaux, le trafic est interrompu entre République et Bastille.' Where is service disrupted?", answer: "Between République and Bastille metro stations due to construction." },
          { q: "9. Announcement: 'La voiture bar se trouve au centre de la rame, en voiture 4.' Where can passengers purchase food?", answer: "Car 4 in the middle of the train." },
          { q: "10. Announcement: 'Mesdames, messieurs, nous arrivons à notre terminus : Paris Gare de Lyon.' What is the destination?", answer: "Final station: Paris Gare de Lyon." },
          { q: "11. Announcement: 'Assurez-vous de n'avoir rien oublié à bord.' What are passengers reminded to do?", answer: "Check that they haven't left any personal belongings on board." },
          { q: "12. Announcement: 'Les passagers avec enfants en bas âge sont invités à embarquer en priorité.' Who boards first?", answer: "Passengers traveling with young children." },
          { q: "13. Announcement: 'Votre attention s'il vous plaît : le vol en provenance de Madrid vient d'atterrir.' What flight has arrived?", answer: "The flight arriving from Madrid." },
          { q: "14. Announcement: 'La distribution des bagages aura lieu au tapis numéro trois.' Where should passengers collect luggage?", answer: "Baggage carousel 3." },
          { q: "15. Announcement: 'Pour rejoindre le centre-ville, prenez la navette bus à la porte 8.' How do passengers get to downtown?", answer: "Take the shuttle bus at Gate 8." },
          { q: "16. Announcement: 'Le contrôleur passera dans quelques instants pour vérifier vos billets.' What should passengers prepare?", answer: "Their tickets for validation by the conductor." },
          { q: "17. Announcement: 'Toute personne sans titre de transport s'expose à une amende.' What is the warning?", answer: "Anyone without a valid ticket faces a fine." },
          { q: "18. Announcement: 'Le service des objets trouvés est situé au niveau moins un.' Where is the lost and found office?", answer: "Basement level (Level -1)." },
          { q: "19. Announcement: 'La circulation des trains reprendra normalement à partir de 15 heures.' When will regular service resume?", answer: "From 3:00 PM (15:00)." },
          { q: "20. Announcement: 'Nous vous souhaitons un agréable voyage en notre compagnie.' What courtesy wish is delivered?", answer: "'We wish you a pleasant journey with us.'" }
        ]
      },
      {
        id: "a1-listening-comprehension-s3",
        sheetNum: 3,
        title: "Sheet 3: Voicemail Prompts & Everyday Dialogue Extraction",
        subtitle: "20 Questions · Understanding caller intents, answering machine messages and street answers",
        exercises: [
          { q: "1. Voicemail message: 'Bonjour, c'est le cabinet médical du docteur Laurent. Votre rendez-vous de demain est déplacé à 11h.' Who called and what is the message?", answer: "Dr. Laurent's medical office; tomorrow's appointment has been rescheduled to 11:00 AM." },
          { q: "2. Voicemail message: 'Ici la pharmacie centrale. Vos médicaments sont prêts, vous pouvez passer jusqu'à 19h30.' What should the recipient do?", answer: "Pick up their medication before 7:30 PM." },
          { q: "3. Voicemail: 'Salut Marc, c'est Thomas. Rappelle-moi sur mon portable dès que possible au 06 20 45 10 99.' What is the callback number?", answer: "06 20 45 10 99" },
          { q: "4. Answering machine prompt: 'Vous êtes bien sur le répondeur de Sophie Martin. Veuillez laisser un message après le bip sonore.' What does the caller hear?", answer: "Sophie Martin's voicemail; leave a message after the tone." },
          { q: "5. Customer service IVR: 'Pour joindre un conseiller commercial, tapez 1. Pour le support technique, tapez 2.' Which key connects to sales?", answer: "Key 1 (tapez 1)." },
          { q: "6. Customer service IVR: 'Pour renouveler votre abonnement, restez en ligne.' What should you do to renew?", answer: "Stay on the line (restez en ligne)." },
          { q: "7. Dialogue: 'Passant : Pardon monsieur, où est la poste ? Piéton : Prenez la première rue à droite, c'est en face de la banque.' Where is the post office?", answer: "First street on the right, opposite the bank." },
          { q: "8. Dialogue: 'Client : Avez-vous du pain sans gluten ? Boulanger : Non, désolé, uniquement du pain de seigle et de campagne.' Does the bakery have gluten-free bread?", answer: "No, only rye bread and country bread." },
          { q: "9. Dialogue: 'Voyageur : Combien de temps pour aller à l'aéroport en métro ? Agent : Il faut compter environ quarante-cinq minutes.' How long is the metro ride?", answer: "Approximately 45 minutes." },
          { q: "10. Voicemail: 'Bonjour madame, ici la médiathèque. Le livre que vous avez réservé est disponible.' Which item is ready?", answer: "The reserved book at the media library." },
          { q: "11. Voicemail: 'Bonjour, c'est le garage Renault. Votre véhicule est réparé, le montant de la facture est de 185 euros.' What is the repair bill?", answer: "185 €" },
          { q: "12. Dialogue: 'Serveur : L'eau plate ou gazeuse ? Client : Gazeuse, s'il vous plaît.' What water was chosen?", answer: "Sparkling water." },
          { q: "13. Dialogue: 'Client : Le musée est gratuit le premier dimanche du mois ? Hôtesse : Oui, pour tout le monde.' When is admission free?", answer: "The first Sunday of the month." },
          { q: "14. Voicemail: 'Chéri, c'est moi. N'oublie pas d'acheter du pain et du beurre avant de rentrer.' What items are requested?", answer: "Bread and butter." },
          { q: "15. Dialogue: 'Hôtel : Le petit-déjeuner est servi de 7h à 10h dans la salle à manger.' What are the breakfast hours?", answer: "From 7:00 AM to 10:00 AM." },
          { q: "16. Voicemail: 'Ici la compagnie d'assurance. Merci de nous renvoyer le formulaire signé avant le 30 septembre.' What is the deadline?", answer: "September 30th." },
          { q: "17. Dialogue: 'Passant : Excusez-moi, ce bus va à la gare Montparnasse ? Chauffeur : Non, vous devez prendre le 91.' Which bus goes to Montparnasse?", answer: "Bus 91." },
          { q: "18. Voicemail: 'Bonjour, c'est l'agence immobilière. La visite de l'appartement est confirmée pour vendredi à 14h.' When is the apartment viewing?", answer: "Friday at 2:00 PM." },
          { q: "19. Dialogue: 'Caissière : Vous avez la carte du magasin ? Client : Non, je ne l'ai pas.' Does the customer have the store loyalty card?", answer: "No." },
          { q: "20. What is the fundamental strategy for DELF A1 listening comprehension?", answer: "Listen for key content words (numbers, times, place names, action verbs) during the first listening, and confirm details during the second listening." }
        ]
      }
    ]
  };

  root.SKILLS_A1_WORKSHEETS = skillsA1Worksheets;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = skillsA1Worksheets;
  }
})(typeof window !== "undefined" ? window : globalThis);
